// Auto-generated Objective-C++ bridge header
// DO NOT EDIT MANUALLY - Generated by tools/generate_bindings.py
// This file will be overwritten when bindings are regenerated

#import <React/RCTBridgeModule.h>

@interface NimBridge : NSObject <RCTBridgeModule>

@end
