/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/nim-rn-monorepo/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/nim-rn-monorepo/bindings/ios-sim/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@scollections@stables.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/nim-rn-monorepo/bindings/ios-sim/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@scollections@stables.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg;
struct tySequence__bk0rMx9cBfS89akAK4U1ghzQ;
struct tySequence__bk0rMx9cBfS89akAK4U1ghzQ_Content;
struct tyTuple__X2l9b8qfQC2TM0v4nyj5Pzw;
struct NimStrPayload;
struct NimStringV2;
struct tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tyObject_NimRawSeq__D0lvs7GEREoKfnigyKSafQ;
struct tySequence__NSxYQOeB3xWzPhqlCq9aFag;
struct tySequence__NSxYQOeB3xWzPhqlCq9aFag_Content;
struct tySequence__bk0rMx9cBfS89akAK4U1ghzQ {
  NI len; tySequence__bk0rMx9cBfS89akAK4U1ghzQ_Content* p;
};
struct tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg {
	tySequence__bk0rMx9cBfS89akAK4U1ghzQ data;
	NI counter;
	NI first;
	NI last;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__X2l9b8qfQC2TM0v4nyj5Pzw {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* Field3;
};
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct tyObject_NimRawSeq__D0lvs7GEREoKfnigyKSafQ {
	NI len;
	void* p;
};
typedef NU8 tyEnum_JsonNodeKind__U4bbm5Gz6WDMmEXMYqG40A;
struct tySequence__NSxYQOeB3xWzPhqlCq9aFag {
  NI len; tySequence__NSxYQOeB3xWzPhqlCq9aFag_Content* p;
};
struct tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__U4bbm5Gz6WDMmEXMYqG40A kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg fields;
} _kind_6;
	struct {
	tySequence__NSxYQOeB3xWzPhqlCq9aFag elems;
} _kind_7;
};
};
struct tySequence__bk0rMx9cBfS89akAK4U1ghzQ_Content { NI cap; tyTuple__X2l9b8qfQC2TM0v4nyj5Pzw data[SEQ_DECL_SIZE]; };
struct tySequence__NSxYQOeB3xWzPhqlCq9aFag_Content { NI cap; tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0);
static N_INLINE(NF, abs__system_u4370)(NF x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pureZjson_u442)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ& s_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u64)(tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u761)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0, NimStringV2 key_p1, NI& hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u589)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1734)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u311)(tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q*& dest_p0, tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* src_p1);
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1086)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u203)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1237)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& t_p0);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1624)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& t_p0, tySequence__bk0rMx9cBfS89akAK4U1ghzQ& data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* val_p3, NI hc_p4, NI h_p5);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2609)(NimStringV2& dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2606)(NimStringV2& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u299)(tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q*& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u85)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1886)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u88)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ& dest_p0, tySequence__bk0rMx9cBfS89akAK4U1ghzQ src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZjson_u104)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ& s_p0, NI newlen_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[47+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_7 = { 47 | NIM_STRLIT_FLAG, "hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_8 = {47, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_7};
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, abs__system_u4370)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	auto T1_ = toFloat__system_u1676(a_p0);
	auto T2_ = toFloat__system_u1676(b_p1);
	NF floatProd = ((NF)(T1_) * (NF)(T2_));
	auto T3_ = toFloat__system_u1676(r);
	NF resAsFloat = T3_;
	{
		if (!(resAsFloat == floatProd)) goto LA6_;
{		(*res_p2) = r;
}	}
	goto LA4_;
LA6_: ;
	{
		{
			auto T11_ = abs__system_u4370(((NF)(resAsFloat) - (NF)(floatProd)));
			auto T12_ = abs__system_u4370(floatProd);
			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{			(*res_p2) = r;
}		}
		goto LA9_;
LA13_: ;
		{
			result = NIM_TRUE;
		}
LA9_: ;
	}
LA4_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_u42)(NI count_p0) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
	result = (NI)0;
	if (nimMulInt(count_p0, ((NI)3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); 	};
	if (nimAddInt((NI)(((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) / (((NI)2))), ((NI)4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); 	};
	result = nextPowerOfTwo__pureZmath_u249((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3));
	return result;
}
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u85)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ dest_p0) {
	NI colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field2.p && !(dest_p0.p->data[colontmp_].Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field2.p);
}
			{
				auto T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_].Field3);
				if (!T6_) goto LA7_;
{				eqdestroy___pureZjson_u64((*dest_p0.p->data[colontmp_].Field3));
				nimRawDispose(dest_p0.p->data[colontmp_].Field3, ((NI)8));
}			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__X2l9b8qfQC2TM0v4nyj5Pzw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u149)(tyTuple__X2l9b8qfQC2TM0v4nyj5Pzw& dest_p0) {
	if (dest_p0.Field2.p && !(dest_p0.Field2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.Field2.p);
}
	{
		auto T3_ = nimDecRefIsLast(dest_p0.Field3);
		if (!T3_) goto LA4_;
{		eqdestroy___pureZjson_u64((*dest_p0.Field3));
		nimRawDispose(dest_p0.Field3, ((NI)8));
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_u428)(NI initialSize_p0, tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* Result) {
	nimZeroMem((void*)Result, sizeof(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg));
	if ((initialSize_p0) < ((NI)0) || (initialSize_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p0, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	auto T1_ = slotsNeeded__pureZcollectionsZtables_u42((initialSize_p0));
	NI correctSizeX60gensym0_ = T1_;
	(*Result).counter = ((NI)0);
	if ((correctSizeX60gensym0_) < ((NI)0) || (correctSizeX60gensym0_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym0_, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	newSeq__pureZjson_u442((*(&(*Result).data)), (correctSizeX60gensym0_));
	(*Result).first = ((NI)-1);
	(*Result).last = ((NI)-1);
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1734)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	auto T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	NI alen = a_p0.len;
	NI blen = b_p1.len;
	{
		if (!(alen == blen)) goto LA3_;
{		{
			if (!(alen == ((NI)0))) goto LA7_;
{			result = NIM_TRUE;
			goto BeforeRet_;
}		}
LA7_: ;
		result = equalMem__system_u1734(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen));
		goto BeforeRet_;
}	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_u34)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;
	if (nimAddInt(h_p0, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) { raiseOverflow(); 	};
	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5) & maxHash_p1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_u761)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0, NimStringV2 key_p1, NI& hc_p2) {
	NI result;
	NI T10_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_6;
{	result = (NI)0;
	hc_p2 = hash__pureZhashes_u589(key_p1);
	{
		if (!(hc_p2 == ((NI)0))) goto LA3_;
{		hc_p2 = ((NI)314159265);
}	}
LA3_: ;
	{
		NI T7_;
		T7_ = (*t_p0).data.len;
		if (!(T7_ == ((NI)0))) goto LA8_;
{		result = ((NI)-1);
		goto BeforeRet_;
}	}
LA8_: ;
	T10_ = ((*t_p0).data.len-1);
	NI h = (NI)(hc_p2 & T10_);
	{
		while (1) {
			NI T20_;
			if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 			}
			auto T13_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 				}
				T16_ = ((*t_p0).data.p->data[h].Field0 == hc_p2);
				if (!(T16_)) goto LA17_;
				if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 				}
				T16_ = eqStrings((*t_p0).data.p->data[h].Field2, key_p1);
LA17_: ;
				if (!T16_) goto LA18_;
{				result = h;
				goto BeforeRet_;
}			}
LA18_: ;
			T20_ = ((*t_p0).data.len-1);
			h = nextTry__pureZcollectionsZtables_u34(h, T20_);
		} LA12: ;
	}
	if (nimSubInt(((NI)-1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_6)) { raiseOverflow(); 	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_6);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_u1086)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_10;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;
	result = (NIM_BOOL)0;
	{
		NI T3_;
		T3_ = (*t_p0).data.len;
		if (!!(((*t_p0).counter < T3_))) goto LA4_;
{		failedAssertImpl__stdZassertions_u203(TM__4SoG2KRQy3oMm9aUzSLtGrA_8);
}	}
LA4_: ;
	T6_ = (NIM_BOOL)0;
	T7_ = (*t_p0).data.len;
	if (nimMulInt(T7_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) { raiseOverflow(); 	};
	if (nimMulInt((*t_p0).counter, ((NI)3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) { raiseOverflow(); 	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9) < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10));
	if (T6_) goto LA8_;
	T9_ = (*t_p0).data.len;
	if (nimSubInt(T9_, (*t_p0).counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) { raiseOverflow(); 	};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11) < ((NI)4));
LA8_: ;
	result = T6_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_u1624)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& t_p0, tySequence__bk0rMx9cBfS89akAK4U1ghzQ& data_p1, NimStringV2 key_p2, tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* val_p3, NI hc_p4, NI h_p5) {
	if (h_p5 < 0 || h_p5 >= data_p1.len){ raiseIndexError2(h_p5,data_p1.len-1); 	}
	eqcopy___system_u2609((*(&data_p1.p->data[h_p5].Field2)), key_p2);
	if (h_p5 < 0 || h_p5 >= data_p1.len){ raiseIndexError2(h_p5,data_p1.len-1); 	}
	eqsink___pureZjson_u311((*&data_p1.p->data[h_p5].Field3), val_p3);
	if (h_p5 < 0 || h_p5 >= data_p1.len){ raiseIndexError2(h_p5,data_p1.len-1); 	}
	data_p1.p->data[h_p5].Field0 = hc_p4;
	if (h_p5 < 0 || h_p5 >= data_p1.len){ raiseIndexError2(h_p5,data_p1.len-1); 	}
	data_p1.p->data[h_p5].Field1 = ((NI)-1);
	{
		if (!(t_p0.first < ((NI)0))) goto LA3_;
{		t_p0.first = h_p5;
}	}
LA3_: ;
	{
		if (!(((NI)0) <= t_p0.last)) goto LA7_;
{		if (t_p0.last < 0 || t_p0.last >= data_p1.len){ raiseIndexError2(t_p0.last,data_p1.len-1); 		}
		data_p1.p->data[t_p0.last].Field1 = h_p5;
}	}
LA7_: ;
	t_p0.last = h_p5;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_u1237)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& t_p0) {
	tySequence__bk0rMx9cBfS89akAK4U1ghzQ n;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
	tySequence__bk0rMx9cBfS89akAK4U1ghzQ T2_;
	n.len = 0; n.p = NIM_NIL;
	T1_ = t_p0.data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); 	};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) < ((NI)0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	newSeq__pureZjson_u442((*(&n)), ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12)));
	NI h = t_p0.first;
	t_p0.first = ((NI)-1);
	t_p0.last = ((NI)-1);
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = t_p0.data;
	t_p0.data = n;
	n = T2_;
	{
		while (1) {
			if (!(((NI)0) <= h)) goto LA4;
			if (h < 0 || h >= n.len){ raiseIndexError2(h,n.len-1); 			}
			NI nxt = n.p->data[h].Field1;
			if (h < 0 || h >= n.len){ raiseIndexError2(h,n.len-1); 			}
			NI eh = n.p->data[h].Field0;
			{
				NimStringV2 colontmpD_;
				NI T10_;
				tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* T15_;
				tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* T16_;
				auto T7_ = isFilled__pureZcollectionsZtables_u31(eh);
				if (!T7_) goto LA8_;
{				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				T10_ = (t_p0.data.len-1);
				NI j = (NI)(eh & T10_);
				{
					while (1) {
						NI T14_;
						if (j < 0 || j >= t_p0.data.len){ raiseIndexError2(j,t_p0.data.len-1); 						}
						auto T13_ = isFilled__pureZcollectionsZtables_u31(t_p0.data.p->data[j].Field0);
						if (!T13_) goto LA12;
						T14_ = (t_p0.data.len-1);
						j = nextTry__pureZcollectionsZtables_u34(j, T14_);
					} LA12: ;
				}
				T15_ = (tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg*)0;
				T15_ = (&t_p0);
				if (h < 0 || h >= n.len){ raiseIndexError2(h,n.len-1); 				}
				colontmpD_ = n.p->data[h].Field2;
				eqwasMoved___system_u2606(n.p->data[h].Field2);
				if (h < 0 || h >= n.len){ raiseIndexError2(h,n.len-1); 				}
				T16_ = NIM_NIL;
				T16_ = n.p->data[h].Field3;
				eqwasMoved___pureZjson_u299(n.p->data[h].Field3);
				if (h < 0 || h >= n.len){ raiseIndexError2(h,n.len-1); 				}
				rawInsert__pureZjson_u1624((*T15_), (*(&t_p0.data)), colontmpD_, T16_, n.p->data[h].Field0, j);
				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
}			}
LA8_: ;
			h = nxt;
		} LA4: ;
	}
	eqdestroy___pureZjson_u85(n);
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_u1886)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (*t_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
{		result = ((NI)-1);
		goto BeforeRet_;
}	}
LA4_: ;
	T6_ = ((*t_p0).data.len-1);
	NI h = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NI T16_;
			if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 			}
			auto T9_ = isFilled__pureZcollectionsZtables_u31((*t_p0).data.p->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 				}
				T12_ = ((*t_p0).data.p->data[h].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h < 0 || h >= (*t_p0).data.len){ raiseIndexError2(h,(*t_p0).data.len-1); 				}
				T12_ = eqStrings((*t_p0).data.p->data[h].Field2, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
{				result = h;
				goto BeforeRet_;
}			}
LA14_: ;
			T16_ = ((*t_p0).data.len-1);
			h = nextTry__pureZcollectionsZtables_u34(h, T16_);
		} LA8: ;
	}
	if (nimSubInt(((NI)-1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); 	};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u693)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& t_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* val_p2) {
	NI T7_;
	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
{		auto T6_ = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
		NI correctSizeX60gensym13_ = T6_;
		t_p0.counter = ((NI)0);
		if ((correctSizeX60gensym13_) < ((NI)0) || (correctSizeX60gensym13_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym13_, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		newSeq__pureZjson_u442((*(&t_p0.data)), (correctSizeX60gensym13_));
		t_p0.first = ((NI)-1);
		t_p0.last = ((NI)-1);
}	}
LA4_: ;
	T7_ = (NI)0;
	NI hc = T7_;
	auto T8_ = rawGet__pureZjson_u761((&t_p0), key_p1, (*(&hc)));
	NI index = T8_;
	{
		if (!(((NI)0) <= index)) goto LA11_;
{		if (index < 0 || index >= t_p0.data.len){ raiseIndexError2(index,t_p0.data.len-1); 		}
		eqsink___pureZjson_u311((*&t_p0.data.p->data[index].Field3), val_p2);
}	}
	goto LA9_;
LA11_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
		tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* T25_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_15;
		{
			NI T16_;
			T16_ = t_p0.data.len;
			if (!(T16_ == ((NI)0))) goto LA17_;
{			auto T19_ = slotsNeeded__pureZcollectionsZtables_u42(((NI)32));
			NI correctSizeX60gensym18_ = T19_;
			t_p0.counter = ((NI)0);
			if ((correctSizeX60gensym18_) < ((NI)0) || (correctSizeX60gensym18_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym18_, ((NI)0), ((NI)IL64(9223372036854775807))); 			}
			newSeq__pureZjson_u442((*(&t_p0.data)), (correctSizeX60gensym18_));
			t_p0.first = ((NI)-1);
			t_p0.last = ((NI)-1);
}		}
LA17_: ;
		{
			auto T22_ = mustRehash__pureZjson_u1086((&t_p0));
			if (!T22_) goto LA23_;
{			enlarge__pureZjson_u1237((*(&t_p0)));
			index = rawGetKnownHC__pureZjson_u1886((&t_p0), key_p1, hc);
}		}
LA23_: ;
		if (nimSubInt(((NI)-1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); 		};
		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14);
		T25_ = (tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg*)0;
		T25_ = (&t_p0);
		tyObject_JsonNodeObj__PYN2mevIEJNL4RaHoYJW5Q* blitTmp = val_p2;
		rawInsert__pureZjson_u1624((*T25_), (*(&t_p0.data)), key_p1, blitTmp, hc, index);
		if (nimAddInt(t_p0.counter, ((NI)1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_15)) { raiseOverflow(); 		};
		t_p0.counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_15);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__D0lvs7GEREoKfnigyKSafQ*) (x_p0))).p == (*((tyObject_NimRawSeq__D0lvs7GEREoKfnigyKSafQ*) (y_p1))).p);
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_16;
	auto T1_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	if (nimAddInt((*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc, ((NI)8), &TM__4SoG2KRQy3oMm9aUzSLtGrA_16)) { raiseOverflow(); 	};
	(*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_16);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u88)(tySequence__bk0rMx9cBfS89akAK4U1ghzQ& dest_p0, tySequence__bk0rMx9cBfS89akAK4U1ghzQ src_p1) {
	NI T6_;
{	{
		auto T3_ = sameSeqPayload((&dest_p0), (&src_p1));
		if (!T3_) goto LA4_;
{		goto BeforeRet_;
}	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pureZjson_u104((*(&dest_p0)), T6_);
	NI colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = dest_p0.len;
			if (!(colontmp_ < T9_)) goto LA8;
			dest_p0.p->data[colontmp_].Field0 = src_p1.p->data[colontmp_].Field0;
			dest_p0.p->data[colontmp_].Field1 = src_p1.p->data[colontmp_].Field1;
			eqcopy___system_u2609((*(&dest_p0.p->data[colontmp_].Field2)), src_p1.p->data[colontmp_].Field2);
			{
				if (!src_p1.p->data[colontmp_].Field3) goto LA12_;
{				nimIncRef(src_p1.p->data[colontmp_].Field3);
}			}
LA12_: ;
			{
				auto T16_ = nimDecRefIsLast(dest_p0.p->data[colontmp_].Field3);
				if (!T16_) goto LA17_;
{				eqdestroy___pureZjson_u64((*dest_p0.p->data[colontmp_].Field3));
				nimRawDispose(dest_p0.p->data[colontmp_].Field3, ((NI)8));
}			}
LA17_: ;
			dest_p0.p->data[colontmp_].Field3 = src_p1.p->data[colontmp_].Field3;
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u460)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& dest_p0, tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg* src_p1) {
	eqcopy___pureZjson_u88((*(&dest_p0.data)), (*src_p1).data);
	dest_p0.counter = (*src_p1).counter;
	dest_p0.first = (*src_p1).first;
	dest_p0.last = (*src_p1).last;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u457)(tyObject_OrderedTable__l4iki9aTokS3EF5JWwb4WPg& dest_p0) {
	eqdestroy___pureZjson_u85(dest_p0.data);
}
