/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sfaststreams-0.3.0-537acd856f131772e5553318f53bf1263935034a@sfaststreams@sbuffers.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sfaststreams-0.3.0-537acd856f131772e5553318f53bf1263935034a@sfaststreams@sbuffers.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#include <exception>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content;
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
struct tyObject_Deque__du7hawUjwrOv3acirvjaug;
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA;
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct NimStrPayload;
struct NimStringV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g {
  NI len; tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ {
	NI consumedTo;
	NI writtenTo;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* data;
};
struct tyObject_Deque__du7hawUjwrOv3acirvjaug {
	tySequence__a5J6HCFyQ89bjZwQcmZVP4g data;
	NU head;
	NU tail;
};
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg {
	NI pageSize;
	NI maxBufferedBytes;
	tyObject_Deque__du7hawUjwrOv3acirvjaug queue;
	NIM_BOOL eofReached;
	NI fauxEofPos;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w : public Exception {
};
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w {
	NU8* startAddr;
	NU8* endAddr;
};
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content { NI cap; tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u400)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u417)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZtimes_u2467)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0);
static N_INLINE(NF, abs__system_u4370)(NF x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZbuffers_u248)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u260)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ& dest_p0);
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, peekLast__pkgZfaststreamsZbuffers_u586)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u242)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u245)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, addWritablePage__pkgZfaststreamsZbuffers_u655)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI pageSize_p1);
N_LIB_PRIVATE N_NIMCALL(void, trackWrittenToEnd__pkgZfaststreamsZbuffers_u568)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*, new__pkgZfaststreamsZbuffers_u694)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZtimes_u2476)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ& dest_p0, tySequence__6H5Oh5UUvVCLiakt9aTwtUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeqUninitialized__pkgZfaststreamsZbuffers_u668)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, addLast__pkgZfaststreamsZbuffers_u728)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* item_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, eqdup___pkgZfaststreamsZbuffers_u251)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p0);
N_LIB_PRIVATE N_NIMCALL(NU8*, baseAddr__pkgZfaststreamsZbuffers_u62)(NU8* x_p0, NI x_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, pageLen__pkgZfaststreamsZbuffers_u104)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0);
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, X5BX5D___pkgZfaststreamsZbuffers_u145)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0, NI i_p1);
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, popFirst__pkgZfaststreamsZbuffers_u214)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0);
extern TNimTypeV2 NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_;
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__eXQvBPq9c1e9a9cnoIGLerKnQ_7 = { 12 | NIM_STRLIT_FLAG, "Empty deque." };
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_8 = {12, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_7};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__eXQvBPq9c1e9a9cnoIGLerKnQ_10 = { 15 | NIM_STRLIT_FLAG, "Out of bounds: " };
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_11 = {15, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_10};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__eXQvBPq9c1e9a9cnoIGLerKnQ_14 = { 3 | NIM_STRLIT_FLAG, " > " };
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_15 = {3, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_14};
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_17 = {15, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_10};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__eXQvBPq9c1e9a9cnoIGLerKnQ_18 = { 4 | NIM_STRLIT_FLAG, " < 0" };
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_19 = {4, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_18};
static const NimStringV2 TM__eXQvBPq9c1e9a9cnoIGLerKnQ_23 = {12, (NimStrPayload*)&TM__eXQvBPq9c1e9a9cnoIGLerKnQ_7};
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_2;
	auto T1_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	if (nimAddInt((*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc, ((NI)8), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_2)) { raiseOverflow(); 	};
	(*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_2);
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_3;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_3)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_3);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u260)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.data);
		if (!T3_) goto LA4_;
{		eqdestroy___pureZtimes_u2467((*dest_p0.data));
		nimRawDispose(dest_p0.data, ((NI)8));
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u400)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg& dest_p0) {
	eqdestroy___pkgZfaststreamsZbuffers_u417(dest_p0.queue.data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZbuffers_u549)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*& dest_p0, tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* src_p1) {
	{
		if (!src_p1) goto LA3_;
{		nimIncRef(src_p1);
}	}
LA3_: ;
	{
		auto T7_ = nimDecRefIsLast(dest_p0);
		if (!T7_) goto LA8_;
{		eqdestroy___pkgZfaststreamsZbuffers_u400((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
}	}
LA8_: ;
	dest_p0 = src_p1;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == ((NI)(IL64(-9223372036854775807) - IL64(1))));
		if (!(T3_)) goto LA4_;
		T3_ = (b_p1 == ((NI)-1));
LA4_: ;
		if (!T3_) goto LA5_;
{		result = NIM_TRUE;
}	}
	goto LA1_;
LA5_: ;
	{
		(*res_p2) = (NI)(a_p0 / b_p1);
	}
LA1_: ;
	return result;
}
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, abs__system_u4370)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	auto T1_ = toFloat__system_u1676(a_p0);
	auto T2_ = toFloat__system_u1676(b_p1);
	NF floatProd = ((NF)(T1_) * (NF)(T2_));
	auto T3_ = toFloat__system_u1676(r);
	NF resAsFloat = T3_;
	{
		if (!(resAsFloat == floatProd)) goto LA6_;
{		(*res_p2) = r;
}	}
	goto LA4_;
LA6_: ;
	{
		{
			auto T11_ = abs__system_u4370(((NF)(resAsFloat) - (NF)(floatProd)));
			auto T12_ = abs__system_u4370(floatProd);
			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{			(*res_p2) = r;
}		}
		goto LA9_;
LA13_: ;
		{
			result = NIM_TRUE;
		}
LA9_: ;
	}
LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nextAlignedSize__pkgZfaststreamsZbuffers_u930)(NI minSize_p0, NI pageSize_p1) {
	NI result;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_4;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_5;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6;
	result = (NI)0;
	if (pageSize_p1 == 0){ raiseDivByZero(); 	}
	if (nimDivInt(minSize_p0, pageSize_p1, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_4)) { raiseOverflow(); 	};
	if (nimAddInt((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_4), ((NI)1), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_5)) { raiseOverflow(); 	};
	if (nimMulInt((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_5), pageSize_p1, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6)) { raiseOverflow(); 	};
	if (((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6)) < ((NI)0) || ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	result = ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_6));
	return result;
}
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NI result;
	result = (NI)0;
	if ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head)) > (NU)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); 	}
	result = ((NI) ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZbuffers_u248)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1) {
	{
		if (!src_p1) goto LA3_;
{		nimIncRef(src_p1);
}	}
LA3_: ;
	{
		auto T7_ = nimDecRefIsLast(dest_p0);
		if (!T7_) goto LA8_;
{		eqdestroy___pkgZfaststreamsZbuffers_u260((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
}	}
LA8_: ;
	dest_p0 = src_p1;
}
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NU result;
	NI T1_;
	T1_ = (*deq_p0).data.len;
	result = (NU)((NU64)(((NU) (T1_))) - (NU64)(((NU)1)));
	return result;
}
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, peekLast__pkgZfaststreamsZbuffers_u586)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ** result;
	result = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**)0;
	{
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T6_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T3_ < ((NI)1)))) goto LA4_;
{		T6_ = NIM_NIL;
		T6_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T6_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T6_).name = "IndexDefect";
		(*T6_).message = TM__eXQvBPq9c1e9a9cnoIGLerKnQ_8;
		(*T6_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IndexDefect", "peekLast", "deques.nim", 105);
}	}
LA4_: ;
	auto T7_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)((NU)((NU64)(deq_p0.tail) - (NU64)(((NU)1))) & T7_) < 0 || (NU)((NU)((NU64)(deq_p0.tail) - (NU64)(((NU)1))) & T7_) >= deq_p0.data.len){ raiseIndexError2((NU)((NU)((NU64)(deq_p0.tail) - (NU64)(((NU)1))) & T7_),deq_p0.data.len-1); 	}
	result = &deq_p0.data.p->data[(NU)((NU)((NU64)(deq_p0.tail) - (NU64)(((NU)1))) & T7_)];
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u242)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0) {
	dest_p0 = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u245)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
{		eqdestroy___pkgZfaststreamsZbuffers_u260((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, trackWrittenToEnd__pkgZfaststreamsZbuffers_u568)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0) {
	{
		tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page;
		NI T7_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
		if (!(((NI)0) < T3_)) goto LA4_;
{		page = NIM_NIL;
		auto T6_ = peekLast__pkgZfaststreamsZbuffers_u586((*(&(*buffers_p0).queue)));
		eqcopy___pkgZfaststreamsZbuffers_u248((*&page), (*T6_));
		T7_ = (*(*page).data).len;
		if ((T7_) < ((NI)0) || (T7_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T7_, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		(*page).writtenTo = (T7_);
		eqdestroy___pkgZfaststreamsZbuffers_u245(page);
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZfaststreamsZbuffers_u254)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
{		eqdestroy___pkgZfaststreamsZbuffers_u260((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
}	}
LA4_: ;
	dest_p0 = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, eqdup___pkgZfaststreamsZbuffers_u251)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
{		nimIncRef(src_p0);
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, addWritablePage__pkgZfaststreamsZbuffers_u655)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI pageSize_p1) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* resX60gensym41_;
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* colontmpD_;
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* T1_;
	result = NIM_NIL;
	resX60gensym41_ = NIM_NIL;
	colontmpD_ = NIM_NIL;
	trackWrittenToEnd__pkgZfaststreamsZbuffers_u568(buffers_p0);
	T1_ = NIM_NIL;
	T1_ = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*) nimNewObj(sizeof(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ), NIM_ALIGNOF(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ));
	resX60gensym41_ = new__pkgZfaststreamsZbuffers_u694();
	auto T2_ = newSeqUninitialized__pkgZfaststreamsZbuffers_u668(pageSize_p1);
	eqsink___pureZtimes_u2476((*resX60gensym41_), T2_);
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* blitTmp = resX60gensym41_;
	(*T1_).data = blitTmp;
	(*T1_).writtenTo = ((NI)0);
	result = T1_;
	colontmpD_ = eqdup___pkgZfaststreamsZbuffers_u251(result);
	addLast__pkgZfaststreamsZbuffers_u728((*(&(*buffers_p0).queue)), colontmpD_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, getWritablePage__pkgZfaststreamsZbuffers_u878)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI preferredSize_p1) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* result;
{	result = NIM_NIL;
	{
		tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* lastPage;
		std::exception_ptr T7_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
		if (!(((NI)0) < T3_)) goto LA4_;
{		lastPage = NIM_NIL;
		try {
		auto T8_ = peekLast__pkgZfaststreamsZbuffers_u586((*(&(*buffers_p0).queue)));
		eqcopy___pkgZfaststreamsZbuffers_u248((*&lastPage), (*T8_));
		{
			NI T11_;
			T11_ = (*(*lastPage).data).len;
			if (!((*lastPage).writtenTo < T11_)) goto LA12_;
{			result = lastPage;
			eqwasMoved___pkgZfaststreamsZbuffers_u242((*&lastPage));
			eqdestroy___pkgZfaststreamsZbuffers_u245(lastPage);
			goto BeforeRet_;
}		}
LA12_: ;
		}
		catch (Exception* T8_) {
		T7_ = std::current_exception();
		}
		catch (...) {
			T7_ = std::current_exception();
		}
		{
			eqdestroy___pkgZfaststreamsZbuffers_u245(lastPage);
			if (T7_) std::rethrow_exception(T7_);
		}
}	}
LA4_: ;
	result = addWritablePage__pkgZfaststreamsZbuffers_u655(buffers_p0, preferredSize_p1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8*, readableEnd__pkgZfaststreamsZbuffers_u75)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0) {
	NU8* result;
	result = (NU8*)0;
	NU bytesX60gensym5_ = (NU)((NU64)(((NU) ((*page_p0).writtenTo))) * (NU64)(((NU)1)));
	auto T1_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*page_p0).data)).p) ? ((*(*page_p0).data).p->data) : NIM_NIL, (*(*page_p0).data).len);
	result = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (T1_))))) + (NU64)(((NU) (((NI) (bytesX60gensym5_))))))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u546)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
{		eqdestroy___pkgZfaststreamsZbuffers_u400((*dest_p0));
		nimRawDispose(dest_p0, ((NI)8));
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, pageLen__pkgZfaststreamsZbuffers_u104)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0) {
	NI result;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9;
	result = (NI)0;
	if (nimSubInt((*page_p0).writtenTo, (*page_p0).consumedTo, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9)) { raiseOverflow(); 	};
	if (((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9)) < ((NI)0) || ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	result = ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_9));
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	auto T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1) {
	{
		NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12;
		NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_13;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
{		if (nimAddInt(src_p1.len, ((NI)1), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12)) { raiseOverflow(); 		};
		if (((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12)) < ((NI)0) || ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1726(((void*) ((&(*dest_p0.p).data[dest_p0.len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_12)));
		if (nimAddInt(dest_p0.len, src_p1.len, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_13)) { raiseOverflow(); 		};
		dest_p0.len = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_13);
}	}
LA3_: ;
}
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, X5BX5D___pkgZfaststreamsZbuffers_u145)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0, NI i_p1) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ** result;
{	result = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**)0;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		std::exception_ptr T7_;
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T8_;
		NimStringV2 T9_;
		NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_16;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T3_ <= i_p1))) goto LA4_;
{		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		try {
		T8_ = NIM_NIL;
		T8_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T8_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T8_).name = "IndexDefect";
		T9_.len = 0; T9_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u8(i_p1);
		auto T10_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (nimSubInt(T10_, ((NI)1), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_16)) { raiseOverflow(); 		};
		colontmpD__2 = dollar___systemZdollars_u8((NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_16));
		T9_ = rawNewString(colontmpD_.len + colontmpD__2.len + 18);
appendString(T9_, TM__eXQvBPq9c1e9a9cnoIGLerKnQ_11);
appendString(T9_, colontmpD_);
appendString(T9_, TM__eXQvBPq9c1e9a9cnoIGLerKnQ_15);
appendString(T9_, colontmpD__2);
		(*T8_).message = T9_;
		(*T8_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T8_, "IndexDefect", "[]", "deques.nim", 111);
		}
		catch (Exception* T8_) {
		T7_ = std::current_exception();
		}
		catch (...) {
			T7_ = std::current_exception();
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (T7_) std::rethrow_exception(T7_);
		}
}	}
LA4_: ;
	{
		NimStringV2 colontmpD__3;
		std::exception_ptr T18_;
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T19_;
		NimStringV2 T20_;
		if (!NIM_UNLIKELY((i_p1 < ((NI)0)))) goto LA15_;
{		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		try {
		T19_ = NIM_NIL;
		T19_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T19_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T19_).name = "IndexDefect";
		T20_.len = 0; T20_.p = NIM_NIL;
		colontmpD__3 = dollar___systemZdollars_u8(i_p1);
		T20_ = rawNewString(colontmpD__3.len + 19);
appendString(T20_, TM__eXQvBPq9c1e9a9cnoIGLerKnQ_17);
appendString(T20_, colontmpD__3);
appendString(T20_, TM__eXQvBPq9c1e9a9cnoIGLerKnQ_19);
		(*T19_).message = T20_;
		(*T19_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T19_, "IndexDefect", "[]", "deques.nim", 114);
		}
		catch (Exception* T19_) {
		T18_ = std::current_exception();
		}
		catch (...) {
			T18_ = std::current_exception();
		}
		{
			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			if (T18_) std::rethrow_exception(T18_);
		}
}	}
LA15_: ;
	auto T23_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (i_p1)))) & T23_) < 0 || (NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (i_p1)))) & T23_) >= deq_p0.data.len){ raiseIndexError2((NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (i_p1)))) & T23_),deq_p0.data.len-1); 	}
	result = &deq_p0.data.p->data[(NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (i_p1)))) & T23_)];
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, totalBufferedBytes__pkgZfaststreamsZbuffers_u1026)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0) {
	NI result;
	result = (NI)0;
	{
		NI i;
		NI colontmp_;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
		NI i_2 = ((NI)0);
		{
			while (1) {
				NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_20;
				NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_21;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				if ((i) < ((NI)0) || (i) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(i, ((NI)0), ((NI)IL64(9223372036854775807))); 				}
				auto T4_ = X5BX5D___pkgZfaststreamsZbuffers_u145((*(&(*buffers_p0).queue)), (i));
				auto T5_ = pageLen__pkgZfaststreamsZbuffers_u104((*T4_));
				if (nimAddInt(result, T5_, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_20)) { raiseOverflow(); 				};
				if (TM__eXQvBPq9c1e9a9cnoIGLerKnQ_20 < 0 || TM__eXQvBPq9c1e9a9cnoIGLerKnQ_20 > IL64(9223372036854775807)){ raiseOverflow(); 				}
				result = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_20);
				if (nimAddInt(i_2, ((NI)1), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_21)) { raiseOverflow(); 				};
				i_2 = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_21);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, popFirst__pkgZfaststreamsZbuffers_u214)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* result;
	result = NIM_NIL;
	{
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T6_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T3_ < ((NI)1)))) goto LA4_;
{		T6_ = NIM_NIL;
		T6_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T6_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T6_).name = "IndexDefect";
		(*T6_).message = TM__eXQvBPq9c1e9a9cnoIGLerKnQ_23;
		(*T6_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IndexDefect", "popFirst", "deques.nim", 105);
}	}
LA4_: ;
	auto T7_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)(deq_p0.head & T7_) < 0 || (NU)(deq_p0.head & T7_) >= deq_p0.data.len){ raiseIndexError2((NU)(deq_p0.head & T7_),deq_p0.data.len-1); 	}
	result = deq_p0.data.p->data[(NU)(deq_p0.head & T7_)];
	eqwasMoved___pkgZfaststreamsZbuffers_u242(deq_p0.data.p->data[(NU)(deq_p0.head & T7_)]);
	deq_p0.head += ((NI)1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w, obtainReadableSpan__pkgZfaststreamsZbuffers_u113)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI& currentSpanEndPos_p1) {
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w result;
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page;
	NI colontmpD_;
	NI colontmpD__2;
	NU8* colontmpD__3;
	std::exception_ptr T2_;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_22;
	NI T21_;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_26;
	NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_27;
{	nimZeroMem((void*)(&result), sizeof(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w));
	page = NIM_NIL;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NU8*)0;
	try {
	{
		auto T5_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
		if (!(T5_ == ((NI)0))) goto LA6_;
{		nimZeroMem((void*)(&result), sizeof(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w));
		eqdestroy___pkgZfaststreamsZbuffers_u245(page);
		goto BeforeRet_;
}	}
LA6_: ;
	auto T8_ = X5BX5D___pkgZfaststreamsZbuffers_u145((*(&(*buffers_p0).queue)), ((NI)0));
	eqcopy___pkgZfaststreamsZbuffers_u248((*&page), (*T8_));
	if (nimSubInt((*page).writtenTo, (*page).consumedTo, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_22)) { raiseOverflow(); 	};
	NI unconsumedLen = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_22);
	{
		if (!(unconsumedLen == ((NI)0))) goto LA11_;
{		{
			tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* colontmpD__4;
			NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_24;
			auto T15_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
			if (!(((NI)1) < T15_)) goto LA16_;
{			colontmpD__4 = NIM_NIL;
			colontmpD__4 = popFirst__pkgZfaststreamsZbuffers_u214((*(&(*buffers_p0).queue)));
			(void)(colontmpD__4);
			auto T18_ = X5BX5D___pkgZfaststreamsZbuffers_u145((*(&(*buffers_p0).queue)), ((NI)0));
			eqcopy___pkgZfaststreamsZbuffers_u248((*&page), (*T18_));
			if (nimSubInt((*page).writtenTo, (*page).consumedTo, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_24)) { raiseOverflow(); 			};
			unconsumedLen = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_24);
			eqdestroy___pkgZfaststreamsZbuffers_u245(colontmpD__4);
}		}
		goto LA13_;
LA16_: ;
		{
			nimZeroMem((void*)(&result), sizeof(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w));
			eqdestroy___pkgZfaststreamsZbuffers_u245(page);
			goto BeforeRet_;
		}
LA13_: ;
}	}
LA11_: ;
	auto T20_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*page).data)).p) ? ((*(*page).data).p->data) : NIM_NIL, (*(*page).data).len);
	NU8* baseAddr = T20_;
	NU bytesX60gensym18_ = (NU)((NU64)(((NU) ((*page).consumedTo))) * (NU64)(((NU)1)));
	NU8* startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (baseAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym18_))))))))));
	T21_ = (NI)0;
	{
		NI colontmpD__5;
		NI colontmpD__6;
		NI TM__eXQvBPq9c1e9a9cnoIGLerKnQ_25;
		if (!!(((*buffers_p0).fauxEofPos == ((NI)0)))) goto LA24_;
{		colontmpD__5 = (NI)0;
		colontmpD__6 = (NI)0;
		if (nimSubInt((*buffers_p0).fauxEofPos, currentSpanEndPos_p1, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_25)) { raiseOverflow(); 		};
		NI maxSize = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_25);
		{
			if (!(maxSize < unconsumedLen)) goto LA28_;
{			colontmpD__5 = maxSize;
			colontmpD_ = colontmpD__5;
}		}
		goto LA26_;
LA28_: ;
		{
			colontmpD__6 = unconsumedLen;
			colontmpD_ = colontmpD__6;
		}
LA26_: ;
		T21_ = colontmpD_;
}	}
	goto LA22_;
LA24_: ;
	{
		colontmpD__2 = unconsumedLen;
		T21_ = colontmpD__2;
	}
LA22_: ;
	NI usableLen = T21_;
	if (nimAddInt((*page).consumedTo, usableLen, &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_26)) { raiseOverflow(); 	};
	(*page).consumedTo = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_26);
	if ((usableLen) < ((NI)0) || (usableLen) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(usableLen, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	if (nimAddInt(currentSpanEndPos_p1, (usableLen), &TM__eXQvBPq9c1e9a9cnoIGLerKnQ_27)) { raiseOverflow(); 	};
	if (TM__eXQvBPq9c1e9a9cnoIGLerKnQ_27 < 0 || TM__eXQvBPq9c1e9a9cnoIGLerKnQ_27 > IL64(9223372036854775807)){ raiseOverflow(); 	}
	currentSpanEndPos_p1 = (NI)(TM__eXQvBPq9c1e9a9cnoIGLerKnQ_27);
	result.startAddr = startAddr;
	NU bytesX60gensym21_ = (NU)((NU64)(((NU) (usableLen))) * (NU64)(((NU)1)));
	colontmpD__3 = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym21_))))))))));
	result.endAddr = colontmpD__3;
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		eqdestroy___pkgZfaststreamsZbuffers_u245(page);
		if (T2_) std::rethrow_exception(T2_);
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8*, readableStart__pkgZfaststreamsZbuffers_u59)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0) {
	NU8* result;
	result = (NU8*)0;
	NU bytesX60gensym2_ = (NU)((NU64)(((NU) ((*page_p0).consumedTo))) * (NU64)(((NU)1)));
	auto T1_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*page_p0).data)).p) ? ((*(*page_p0).data).p->data) : NIM_NIL, (*(*page_p0).data).len);
	result = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (T1_))))) + (NU64)(((NU) (((NI) (bytesX60gensym2_))))))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*, initPageBuffers__pkgZfaststreamsZbuffers_u393)(NI pageSize_p0, NI maxBufferedBytes_p1) {
	tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* result;
{	result = NIM_NIL;
	{
		NI colontmpD_;
		NI colontmpD__2;
		tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* T5_;
		if (!(((NI)0) < pageSize_p0)) goto LA3_;
{		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		T5_ = NIM_NIL;
		T5_ = (tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) nimNewObj(sizeof(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg), NIM_ALIGNOF(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg));
		colontmpD_ = pageSize_p0;
		(*T5_).pageSize = colontmpD_;
		colontmpD__2 = maxBufferedBytes_p1;
		(*T5_).maxBufferedBytes = colontmpD__2;
		result = T5_;
		goto BeforeRet_;
}	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w, fullSpan__pkgZfaststreamsZbuffers_u377)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0) {
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w result;
	NU8* colontmpD_;
	NI T2_;
	nimZeroMem((void*)(&result), sizeof(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w));
	colontmpD_ = (NU8*)0;
	auto T1_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*page_p0).data)).p) ? ((*(*page_p0).data).p->data) : NIM_NIL, (*(*page_p0).data).len);
	NU8* baseAddr = T1_;
	result.startAddr = baseAddr;
	T2_ = (*(*page_p0).data).len;
	NU bytesX60gensym29_ = (NU)((NU64)(((NU) (T2_))) * (NU64)(((NU)1)));
	colontmpD_ = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (baseAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym29_))))))))));
	result.endAddr = colontmpD_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w, writableSpan__pkgZfaststreamsZbuffers_u355)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0) {
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w result;
	NU8* colontmpD_;
	NU8* colontmpD__2;
	NI T2_;
	nimZeroMem((void*)(&result), sizeof(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w));
	colontmpD_ = (NU8*)0;
	colontmpD__2 = (NU8*)0;
	auto T1_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*page_p0).data)).p) ? ((*(*page_p0).data).p->data) : NIM_NIL, (*(*page_p0).data).len);
	NU8* baseAddr = T1_;
	NU bytesX60gensym24_ = (NU)((NU64)(((NU) ((*page_p0).writtenTo))) * (NU64)(((NU)1)));
	colontmpD_ = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (baseAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym24_))))))))));
	result.startAddr = colontmpD_;
	T2_ = (*(*page_p0).data).len;
	NU bytesX60gensym26_ = (NU)((NU64)(((NU) (T2_))) * (NU64)(((NU)1)));
	colontmpD__2 = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (baseAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym26_))))))))));
	result.endAddr = colontmpD__2;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, trackWrittenTo__pkgZfaststreamsZbuffers_u611)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NU8* spanHeadPos_p1) {
	{
		NIM_BOOL T3_;
		NI T5_;
		tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* topPage;
		T3_ = (NIM_BOOL)0;
		T3_ = !((buffers_p0 == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T5_ = (NI)0;
		T5_ = len__pkgZfaststreamsZbuffers_u124((&(*buffers_p0).queue));
		T3_ = (((NI)0) < T5_);
LA4_: ;
		if (!T3_) goto LA6_;
{		topPage = NIM_NIL;
		auto T8_ = peekLast__pkgZfaststreamsZbuffers_u586((*(&(*buffers_p0).queue)));
		eqcopy___pkgZfaststreamsZbuffers_u248((*&topPage), (*T8_));
		auto T9_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*topPage).data)).p) ? ((*(*topPage).data).p->data) : NIM_NIL, (*(*topPage).data).len);
		if (((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (spanHeadPos_p1))))) - (NU64)(((NU) (ptrdiff_t) (((void*) (T9_))))))))) / (((NI)1)))) < ((NI)0) || ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (spanHeadPos_p1))))) - (NU64)(((NU) (ptrdiff_t) (((void*) (T9_))))))))) / (((NI)1)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (spanHeadPos_p1))))) - (NU64)(((NU) (ptrdiff_t) (((void*) (T9_))))))))) / (((NI)1))), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		(*topPage).writtenTo = ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (spanHeadPos_p1))))) - (NU64)(((NU) (ptrdiff_t) (((void*) (T9_))))))))) / (((NI)1))));
		eqdestroy___pkgZfaststreamsZbuffers_u245(topPage);
}	}
LA6_: ;
}
