/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@ssystem@sexceptions.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@ssystem@sexceptions.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct TNimTypeV2;
struct tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w;
struct Exception;
struct RootObj;
struct NimStrPayload;
struct NimStringV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA;
struct tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA;
struct tyObject_ArithmeticDefect__9attgTenyfoghyT9cxOAxAug;
struct tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg;
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ;
struct tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA;
struct tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA;
struct tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w : public Exception {
};
struct tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_ArithmeticDefect__9attgTenyfoghyT9cxOAxAug : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA : public tyObject_ArithmeticDefect__9attgTenyfoghyT9cxOAxAug {
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
	NI32 errorCode;
};
struct tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
struct tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA : public tyObject_ArithmeticDefect__9attgTenyfoghyT9cxOAxAug {
};
struct tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3847)(tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ& dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u69)(tySequence__U3NvoVpKEobw8JVQGjnwkQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3899)(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4226)(tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u54)(tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4079)(tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u7802)(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4275)(tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u36)(tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4166)(tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg& dest_p0);
N_LIB_PRIVATE TNimTypeV2 NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__yFSIRpL8lxbVATOmoycAqA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__KT7ZILnJJsmTzdP89bFVGmg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__WAMQ8DZVBMAmCEoSR686dA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__X2fFcb4l5PDxZRUdSuc2kA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__kaxIShWZWaQfmILjO9a9buhg_;
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 1903600640, 2845619456};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 1903600640, 858516224};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[5] = {3701606400, 1285336064, 1903600640, 3680521472, 1418216960};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_6[4] = {3701606400, 1285336064, 4051228160, 2782592256};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 1903600640, 1054416896};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_8[4] = {3701606400, 1285336064, 4051228160, 371506688};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[5] = {3701606400, 1285336064, 1903600640, 3680521472, 51441664};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[4] = {3701606400, 1285336064, 1903600640, 1740992768};
static NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[4] = {3701606400, 1285336064, 1903600640, 2890418688};
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__TzI3paKQY09cLjc9cmCvur3A_2;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__TzI3paKQY09cLjc9cmCvur3A_2)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_2);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3847)(tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
	eqdestroy___system_u3847((*(&(*((tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3899)(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
	eqdestroy___system_u3899((*(&(*((tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4226)(tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u60)(void* dest_p0) {
	eqdestroy___system_u4226((*(&(*((tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZoserrors_u54)(tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
	eqdestroy___stdZoserrors_u54((*(&(*((tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4079)(tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
	eqdestroy___system_u4079((*(&(*((tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u7802)(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u66)(void* dest_p0) {
	eqdestroy___system_u7802((*(&(*((tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4275)(tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u68)(void* dest_p0) {
	eqdestroy___system_u4275((*(&(*((tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_u36)(tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u70)(void* dest_p0) {
	eqdestroy___stdZassertions_u36((*(&(*((tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4166)(tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.parent);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.parent);
}	}
LA4_: ;
	if (dest_p0.message.p && !(dest_p0.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.message.p);
}
	eqdestroy___stdZassertions_u69(dest_p0.trace);
	{
		auto T8_ = nimDecRefIsLast(dest_p0.up);
		if (!T8_) goto LA9_;
{		nimDestroyAndDispose(dest_p0.up);
}	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u72)(void* dest_p0) {
	eqdestroy___system_u4166((*(&(*((tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystematsexceptionsdotnim_DatInit000)(void) {
NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.destructor = (void*)rttiDestroy__systemZexceptions_u56; NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.traceImpl = (void*)NIM_NIL; NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.size = sizeof(tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ); NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__1KmctZ9aFrTVjRwM9cpawW9bQ); NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.depth = 3; NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.flags = 0;NTIv2__1KmctZ9aFrTVjRwM9cpawW9bQ_.display = TM__TzI3paKQY09cLjc9cmCvur3A_3;
NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.destructor = (void*)rttiDestroy__systemZexceptions_u58; NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.traceImpl = (void*)NIM_NIL; NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.size = sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA); NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA); NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.depth = 3; NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.flags = 0;NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_.display = TM__TzI3paKQY09cLjc9cmCvur3A_4;
NTIv2__yFSIRpL8lxbVATOmoycAqA_.destructor = (void*)rttiDestroy__systemZexceptions_u60; NTIv2__yFSIRpL8lxbVATOmoycAqA_.traceImpl = (void*)NIM_NIL; NTIv2__yFSIRpL8lxbVATOmoycAqA_.size = sizeof(tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA); NTIv2__yFSIRpL8lxbVATOmoycAqA_.align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__yFSIRpL8lxbVATOmoycAqA); NTIv2__yFSIRpL8lxbVATOmoycAqA_.depth = 4; NTIv2__yFSIRpL8lxbVATOmoycAqA_.flags = 0;NTIv2__yFSIRpL8lxbVATOmoycAqA_.display = TM__TzI3paKQY09cLjc9cmCvur3A_5;
NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.destructor = (void*)rttiDestroy__systemZexceptions_u62; NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.traceImpl = (void*)NIM_NIL; NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.size = sizeof(tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g); NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.align = (NI16) NIM_ALIGNOF(tyObject_OSError__CKXa9cdChIXJmtT9b9aFBEC1g); NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.depth = 3; NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.flags = 0;NTIv2__CKXa9cdChIXJmtT9b9aFBEC1g_.display = TM__TzI3paKQY09cLjc9cmCvur3A_6;
NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.destructor = (void*)rttiDestroy__systemZexceptions_u64; NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.traceImpl = (void*)NIM_NIL; NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.size = sizeof(tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg); NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.align = (NI16) NIM_ALIGNOF(tyObject_ObjectConversionDefect__KT7ZILnJJsmTzdP89bFVGmg); NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.depth = 3; NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.flags = 0;NTIv2__KT7ZILnJJsmTzdP89bFVGmg_.display = TM__TzI3paKQY09cLjc9cmCvur3A_7;
NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.destructor = (void*)rttiDestroy__systemZexceptions_u66; NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.traceImpl = (void*)NIM_NIL; NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.size = sizeof(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ); NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.align = (NI16) NIM_ALIGNOF(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ); NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.depth = 3; NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.flags = 0;NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_.display = TM__TzI3paKQY09cLjc9cmCvur3A_8;
NTIv2__WAMQ8DZVBMAmCEoSR686dA_.destructor = (void*)rttiDestroy__systemZexceptions_u68; NTIv2__WAMQ8DZVBMAmCEoSR686dA_.traceImpl = (void*)NIM_NIL; NTIv2__WAMQ8DZVBMAmCEoSR686dA_.size = sizeof(tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA); NTIv2__WAMQ8DZVBMAmCEoSR686dA_.align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__WAMQ8DZVBMAmCEoSR686dA); NTIv2__WAMQ8DZVBMAmCEoSR686dA_.depth = 4; NTIv2__WAMQ8DZVBMAmCEoSR686dA_.flags = 0;NTIv2__WAMQ8DZVBMAmCEoSR686dA_.display = TM__TzI3paKQY09cLjc9cmCvur3A_9;
NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.destructor = (void*)rttiDestroy__systemZexceptions_u70; NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.traceImpl = (void*)NIM_NIL; NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.size = sizeof(tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA); NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.align = (NI16) NIM_ALIGNOF(tyObject_AssertionDefect__X2fFcb4l5PDxZRUdSuc2kA); NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.depth = 3; NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.flags = 0;NTIv2__X2fFcb4l5PDxZRUdSuc2kA_.display = TM__TzI3paKQY09cLjc9cmCvur3A_10;
NTIv2__kaxIShWZWaQfmILjO9a9buhg_.destructor = (void*)rttiDestroy__systemZexceptions_u72; NTIv2__kaxIShWZWaQfmILjO9a9buhg_.traceImpl = (void*)NIM_NIL; NTIv2__kaxIShWZWaQfmILjO9a9buhg_.size = sizeof(tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg); NTIv2__kaxIShWZWaQfmILjO9a9buhg_.align = (NI16) NIM_ALIGNOF(tyObject_NilAccessDefect__kaxIShWZWaQfmILjO9a9buhg); NTIv2__kaxIShWZWaQfmILjO9a9buhg_.depth = 3; NTIv2__kaxIShWZWaQfmILjO9a9buhg_.flags = 0;NTIv2__kaxIShWZWaQfmILjO9a9buhg_.display = TM__TzI3paKQY09cLjc9cmCvur3A_11;
}

