/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@scollections@sdeques.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@scollections@sdeques.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ;
struct tyObject_Deque__du7hawUjwrOv3acirvjaug;
struct NimStrPayload;
struct NimStringV2;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g {
  NI len; tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content* p;
};
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct tyObject_Deque__du7hawUjwrOv3acirvjaug {
	tySequence__a5J6HCFyQ89bjZwQcmZVP4g data;
	NU head;
	NU tail;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ {
	NI consumedTo;
	NI writtenTo;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* data;
};
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content { NI cap; tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u260)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, expandIfNeeded__pkgZfaststreamsZbuffers_u735)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__pkgZfaststreamsZbuffers_u743)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g& s_p0, NI len_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u203)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__a5J6HCFyQ89bjZwQcmZVP4g, newSeq__pkgZfaststreamsZbuffers_u800)(NI len_p0);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0);
static N_INLINE(NF, abs__system_u4370)(NF x_p0);
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZfaststreamsZbuffers_u254)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u242)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZfaststreamsZbuffers_u426)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g& dest_p0, tySequence__a5J6HCFyQ89bjZwQcmZVP4g src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u417)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u414)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g& dest_p0);
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__NdgYN5HU2ty0qMI5oazWyg_3 = { 36 | NIM_STRLIT_FLAG, "deques.nim(249, 3) `deq.len <= cap` " };
static const NimStringV2 TM__NdgYN5HU2ty0qMI5oazWyg_4 = {36, (NimStrPayload*)&TM__NdgYN5HU2ty0qMI5oazWyg_3};
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__NdgYN5HU2ty0qMI5oazWyg_2;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__NdgYN5HU2ty0qMI5oazWyg_2)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__NdgYN5HU2ty0qMI5oazWyg_2);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u417)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g dest_p0) {
	NI colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				auto T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
{				eqdestroy___pkgZfaststreamsZbuffers_u260((*dest_p0.p->data[colontmp_]));
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
}			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*));
}
}
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NI result;
	result = (NI)0;
	if ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head)) > (NU)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); 	}
	result = ((NI) ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head))));
	return result;
}
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, abs__system_u4370)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	auto T1_ = toFloat__system_u1676(a_p0);
	auto T2_ = toFloat__system_u1676(b_p1);
	NF floatProd = ((NF)(T1_) * (NF)(T2_));
	auto T3_ = toFloat__system_u1676(r);
	NF resAsFloat = T3_;
	{
		if (!(resAsFloat == floatProd)) goto LA6_;
{		(*res_p2) = r;
}	}
	goto LA4_;
LA6_: ;
	{
		{
			auto T11_ = abs__system_u4370(((NF)(resAsFloat) - (NF)(floatProd)));
			auto T12_ = abs__system_u4370(floatProd);
			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{			(*res_p2) = r;
}		}
		goto LA9_;
LA13_: ;
		{
			result = NIM_TRUE;
		}
LA9_: ;
	}
LA4_: ;
	return result;
}
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NU result;
	NI T1_;
	T1_ = (*deq_p0).data.len;
	result = (NU)((NU64)(((NU) (T1_))) - (NU64)(((NU)1)));
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZfaststreamsZbuffers_u426)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g& dest_p0, tySequence__a5J6HCFyQ89bjZwQcmZVP4g src_p1) {
	if (dest_p0.p != src_p1.p) {	eqdestroy___pkgZfaststreamsZbuffers_u417(dest_p0);
	}
dest_p0.len = src_p1.len; dest_p0.p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u414)(tySequence__a5J6HCFyQ89bjZwQcmZVP4g& dest_p0) {
	dest_p0.len = 0; dest_p0.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, expandIfNeeded__pkgZfaststreamsZbuffers_u735)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0) {
	NI T7_;
	{
		NI T3_;
		T3_ = deq_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
{		auto T6_ = nextPowerOfTwo__pureZmath_u249(((NI)4));
		NI correctSizeX60gensym43_ = T6_;
		if ((correctSizeX60gensym43_) < ((NI)0) || (correctSizeX60gensym43_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym43_, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		newSeq__pkgZfaststreamsZbuffers_u743((*(&deq_p0.data)), (correctSizeX60gensym43_));
}	}
LA4_: ;
	T7_ = deq_p0.data.len;
	NI cap = T7_;
	{
		auto T10_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!!((T10_ <= cap))) goto LA11_;
{		failedAssertImpl__stdZassertions_u203(TM__NdgYN5HU2ty0qMI5oazWyg_4);
}	}
LA11_: ;
	{
		tySequence__a5J6HCFyQ89bjZwQcmZVP4g n;
		NI TM__NdgYN5HU2ty0qMI5oazWyg_5;
		tySequence__a5J6HCFyQ89bjZwQcmZVP4g T24_;
		auto T15_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T15_ == cap))) goto LA16_;
{		n.len = 0; n.p = NIM_NIL;
		if (nimMulInt(cap, ((NI)2), &TM__NdgYN5HU2ty0qMI5oazWyg_5)) { raiseOverflow(); 		};
		if (((NI)(TM__NdgYN5HU2ty0qMI5oazWyg_5)) < ((NI)0) || ((NI)(TM__NdgYN5HU2ty0qMI5oazWyg_5)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__NdgYN5HU2ty0qMI5oazWyg_5), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		n = newSeq__pkgZfaststreamsZbuffers_u800(((NI)(TM__NdgYN5HU2ty0qMI5oazWyg_5)));
		NI i = ((NI)0);
		{
			tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ** x;
			x = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**)0;
			{
				NI c;
				NI colontmp_;
				c = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
				NI i_2 = ((NI)0);
				{
					while (1) {
						tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* T23_;
						NI TM__NdgYN5HU2ty0qMI5oazWyg_6;
						NI TM__NdgYN5HU2ty0qMI5oazWyg_7;
						if (!(i_2 < colontmp_)) goto LA21;
						c = i_2;
						auto T22_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
						if ((NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (c)))) & T22_) < 0 || (NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (c)))) & T22_) >= deq_p0.data.len){ raiseIndexError2((NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (c)))) & T22_),deq_p0.data.len-1); 						}
						x = &deq_p0.data.p->data[(NU)((NU)((NU64)(deq_p0.head) + (NU64)(((NU) (c)))) & T22_)];
						if (i < 0 || i >= n.len){ raiseIndexError2(i,n.len-1); 						}
						T23_ = NIM_NIL;
						T23_ = (*x);
						eqwasMoved___pkgZfaststreamsZbuffers_u242((*x));
						eqsink___pkgZfaststreamsZbuffers_u254((*&n.p->data[i]), T23_);
						if (nimAddInt(i, ((NI)1), &TM__NdgYN5HU2ty0qMI5oazWyg_6)) { raiseOverflow(); 						};
						i = (NI)(TM__NdgYN5HU2ty0qMI5oazWyg_6);
						if (nimAddInt(i_2, ((NI)1), &TM__NdgYN5HU2ty0qMI5oazWyg_7)) { raiseOverflow(); 						};
						i_2 = (NI)(TM__NdgYN5HU2ty0qMI5oazWyg_7);
					} LA21: ;
				}
			}
		}
		T24_.len = 0; T24_.p = NIM_NIL;
		T24_ = n;
		eqwasMoved___pkgZfaststreamsZbuffers_u414(n);
		eqsink___pkgZfaststreamsZbuffers_u426((*(&deq_p0.data)), T24_);
		deq_p0.tail = ((NU) (cap));
		deq_p0.head = ((NU)0);
		eqdestroy___pkgZfaststreamsZbuffers_u417(n);
}	}
LA16_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addLast__pkgZfaststreamsZbuffers_u728)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* item_p1) {
	expandIfNeeded__pkgZfaststreamsZbuffers_u735((*(&deq_p0)));
	auto T1_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)(deq_p0.tail & T1_) < 0 || (NU)(deq_p0.tail & T1_) >= deq_p0.data.len){ raiseIndexError2((NU)(deq_p0.tail & T1_),deq_p0.data.len-1); 	}
	eqsink___pkgZfaststreamsZbuffers_u254((*&deq_p0.data.p->data[(NU)(deq_p0.tail & T1_)]), item_p1);
	deq_p0.tail += ((NI)1);
}
