/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@sreader_desc.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@sreader_desc.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <exception>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg;
struct tyObject_JsonError__UCSWBFJG9as09ar9c21Cb9cU7A;
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ;
struct tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA;
struct tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw;
struct tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw;
struct tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ;
struct tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
struct tyObject_JsonError__UCSWBFJG9as09ar9c21Cb9cU7A : public tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ {
};
struct tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg : public tyObject_JsonError__UCSWBFJG9as09ar9c21Cb9cU7A {
	NI line;
	NI col;
};
struct tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
	NimStringV2 encounteredField;
	NCSTRING deserializedType;
};
typedef NU8 tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg;
typedef NU8 tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ;
struct tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
	tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg encountedToken;
	tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ expectedToken;
};
struct tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
	NimStringV2 deserializedField;
	tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* innerException;
};
struct tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
	NIM_BOOL isNegative;
	NU64 absIntVal;
};
struct tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
};
struct tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg : public tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg {
	NCSTRING objectType;
};
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u77)(tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg* err_p0, NimStringV2 filename_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__apiZcore_u28)(NimStringV2& result_p0, NimStringV2 value_p1);
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2& s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pkgZjson95serializationZreader95desc_u92)(NimStringV2& result_p0, NI value_p1);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u206)(Exception*& dest_p0, Exception* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2609)(NimStringV2& dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZjson95serializationZreader95desc_u113)(tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* dest_p0);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u154)(tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, add__system_u2870)(NimStringV2& x_p0, NCSTRING y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u187)(tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pkgZjson95serializationZreader95desc_u214)(NimStringV2& result_p0, tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg value_p1);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pkgZjson95serializationZreader95desc_u228)(NimStringV2& result_p0, tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u243)(tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u281)(tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, valueStr__pkgZjson95serializationZreader95desc_u71)(tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw* err_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2& s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NU64 x_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u314)(tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u347)(tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg* err_p0, NimStringV2 filename_p1);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_2 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_3 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_6 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_7 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_8 = { 33 | NIM_STRLIT_FLAG, ") Error while reading json file: " };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_9 = {33, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_8};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_10 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_11 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_12 = { 20 | NIM_STRLIT_FLAG, ") Unexpected field \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_13 = {20, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_12};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_14 = { 22 | NIM_STRLIT_FLAG, "\' while deserializing " };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_15 = {22, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_14};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_16 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_17 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_18 = { 20 | NIM_STRLIT_FLAG, ") Unexpected token \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_19 = {20, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_18};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_20 = { 15 | NIM_STRLIT_FLAG, "\' in place of \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_21 = {15, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_20};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_22 = { 5 | NIM_STRLIT_FLAG, "value" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_23 = {5, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_22};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_24 = { 12 | NIM_STRLIT_FLAG, "bool literal" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_25 = {12, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_24};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_26 = { 7 | NIM_STRLIT_FLAG, "integer" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_27 = {7, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_26};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_28 = { 25 | NIM_STRLIT_FLAG, "enum value (int / string)" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_29 = {25, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_28};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_30 = { 19 | NIM_STRLIT_FLAG, "enum value (string)" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_31 = {19, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_30};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_32 = { 6 | NIM_STRLIT_FLAG, "number" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_33 = {6, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_32};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_34 = { 6 | NIM_STRLIT_FLAG, "string" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_35 = {6, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_34};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_36 = { 5 | NIM_STRLIT_FLAG, "comma" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_37 = {5, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_36};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_38 = { 5 | NIM_STRLIT_FLAG, "colon" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_39 = {5, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_38};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_40 = { 19 | NIM_STRLIT_FLAG, "array start bracket" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_41 = {19, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_40};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_42 = { 17 | NIM_STRLIT_FLAG, "array end bracker" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_43 = {17, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_42};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_44 = { 20 | NIM_STRLIT_FLAG, "object start bracket" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_45 = {20, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_44};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_46 = { 18 | NIM_STRLIT_FLAG, "object end bracket" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_47 = {18, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_46};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_48 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_49 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_48};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_50 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_51 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_52 = { 45 | NIM_STRLIT_FLAG, ") Exception encountered while deserializing \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_53 = {45, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_52};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_54 = { 4 | NIM_STRLIT_FLAG, "\': [" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_55 = {4, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_54};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_56 = { 2 | NIM_STRLIT_FLAG, "] " };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_57 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_56};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_58 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_59 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_60 = { 13 | NIM_STRLIT_FLAG, ") The value \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_61 = {13, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_60};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_63 = { 33 | NIM_STRLIT_FLAG, "\' is outside of the allowed range" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_64 = {33, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_63};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_65 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_66 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_67 = { 2 | NIM_STRLIT_FLAG, ") " };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_68 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_67};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_69 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_2};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_70 = {2, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_6};
static const struct {
  NI cap; NIM_CHAR data[55+1];
} TM__VP3EmoYo1tNRl6i84zxMzA_71 = { 55 | NIM_STRLIT_FLAG, ") Not all required fields were specified when reading \'" };
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_72 = {55, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_71};
static const NimStringV2 TM__VP3EmoYo1tNRl6i84zxMzA_73 = {1, (NimStrPayload*)&TM__VP3EmoYo1tNRl6i84zxMzA_48};
extern NIM_THREADVAR Exception* currException__system_u3314;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	auto T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1) {
	{
		NI TM__VP3EmoYo1tNRl6i84zxMzA_4;
		NI TM__VP3EmoYo1tNRl6i84zxMzA_5;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
{		if (nimAddInt(src_p1.len, ((NI)1), &TM__VP3EmoYo1tNRl6i84zxMzA_4)) { raiseOverflow(); 		};
		if (((NI)(TM__VP3EmoYo1tNRl6i84zxMzA_4)) < ((NI)0) || ((NI)(TM__VP3EmoYo1tNRl6i84zxMzA_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__VP3EmoYo1tNRl6i84zxMzA_4), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1726(((void*) ((&(*dest_p0.p).data[dest_p0.len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(TM__VP3EmoYo1tNRl6i84zxMzA_4)));
		if (nimAddInt(dest_p0.len, src_p1.len, &TM__VP3EmoYo1tNRl6i84zxMzA_5)) { raiseOverflow(); 		};
		dest_p0.len = (NI)(TM__VP3EmoYo1tNRl6i84zxMzA_5);
}	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3314;
	return result;
}
static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	eqcopy___stdZtypedthreads_u206((*&result), currException__system_u3314);
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u206((*&currException__system_u3314), (*currException__system_u3314).up);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u77)(tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)114));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_3);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_7);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 33);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_9);
			formatValue__apiZcore_u28((*(&fmtRes)), (*err_p0).message);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym2_;
		T3_ = nullptr;
		errX60gensym2_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym2_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym2_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym2_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u154)(tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)168));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_10);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_11);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 20);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_13);
			formatValue__apiZcore_u28((*(&fmtRes)), (*err_p0).encounteredField);
			prepareAdd(fmtRes, 22);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_15);
			add__system_u2870((*(&fmtRes)), (*err_p0).deserializedType);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym4_;
		T3_ = nullptr;
		errX60gensym4_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym4_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym4_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym4_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZjson95serializationZreader95desc_u37)(tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)0):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_23;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)1):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_25;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)2):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_27;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)3):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_29;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)4):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_31;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)5):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_33;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)6):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_35;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)7):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_37;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)8):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_39;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)9):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_41;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)10):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_43;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)11):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_45;
	}
	break;
	case ((tyEnum_ExpectedTokenCategory__53bzMm2xvlHkXC5lwfZCWQ)12):
	{
		result = TM__VP3EmoYo1tNRl6i84zxMzA_47;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u187)(tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)157));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_16);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_17);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 20);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_19);
			formatValue__pkgZjson95serializationZreader95desc_u214((*(&fmtRes)), (*err_p0).encountedToken);
			prepareAdd(fmtRes, 15);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_21);
			formatValue__pkgZjson95serializationZreader95desc_u228((*(&fmtRes)), (*err_p0).expectedToken);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_49);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym7_;
		T3_ = nullptr;
		errX60gensym7_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym7_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym7_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym7_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u243)(tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)215));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_50);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_51);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 45);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_53);
			formatValue__apiZcore_u28((*(&fmtRes)), (*err_p0).deserializedField);
			prepareAdd(fmtRes, 4);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_55);
			add__system_u2870((*(&fmtRes)), (*(*err_p0).innerException).name);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_57);
			formatValue__apiZcore_u28((*(&fmtRes)), (*(*err_p0).innerException).message);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym9_;
		T3_ = nullptr;
		errX60gensym9_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym9_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym9_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym9_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2& s_p0, NIM_CHAR c_p1) {
	NI TM__VP3EmoYo1tNRl6i84zxMzA_62;
	prepareAdd((*(&s_p0)), ((NI)1));
	(*s_p0.p).data[s_p0.len] = c_p1;
	if (nimAddInt(s_p0.len, ((NI)1), &TM__VP3EmoYo1tNRl6i84zxMzA_62)) { raiseOverflow(); 	};
	s_p0.len = (NI)(TM__VP3EmoYo1tNRl6i84zxMzA_62);
	(*s_p0.p).data[s_p0.len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, valueStr__pkgZjson95serializationZreader95desc_u71)(tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw* err_p0) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	{
		if (!(*err_p0).isNegative) goto LA3_;
{		nimAddCharV1(result, 45);
}	}
LA3_: ;
	colontmpD_ = dollar___systemZdollars_u14((*err_p0).absIntVal);
	prepareAdd(result, colontmpD_.len + 0);
appendString(result, colontmpD_);
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u281)(tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			NimStringV2 colontmpD_;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			fmtRes = rawNewString(((NI)132));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_58);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_59);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 13);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_61);
			colontmpD_ = valueStr__pkgZjson95serializationZreader95desc_u71(err_p0);
			formatValue__apiZcore_u28((*(&fmtRes)), colontmpD_);
			prepareAdd(fmtRes, 33);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_64);
			result = fmtRes;
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym12_;
		T3_ = nullptr;
		errX60gensym12_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym12_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym12_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym12_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u314)(tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)83));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_65);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_66);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_68);
			formatValue__apiZcore_u28((*(&fmtRes)), (*err_p0).message);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym14_;
		T3_ = nullptr;
		errX60gensym14_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym14_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym14_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym14_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u347)(tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	std::exception_ptr T3_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	try {
		NimStringV2 T5_;
		T5_.len = 0; T5_.p = NIM_NIL;
		{
			NimStringV2 fmtRes;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			fmtRes = rawNewString(((NI)144));
			formatValue__apiZcore_u28((*(&fmtRes)), filename_p1);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_69);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).line);
			prepareAdd(fmtRes, 2);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_70);
			formatValue__pkgZjson95serializationZreader95desc_u92((*(&fmtRes)), (*err_p0).col);
			prepareAdd(fmtRes, 55);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_72);
			add__system_u2870((*(&fmtRes)), (*err_p0).objectType);
			prepareAdd(fmtRes, 1);
appendString(fmtRes, TM__VP3EmoYo1tNRl6i84zxMzA_73);
			result = fmtRes;
		}
	}
	catch (Exception* T4_) {
	T3_ = std::current_exception();
	if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 2, 4051228160)) {
		tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA* errX60gensym16_;
		T3_ = nullptr;
		errX60gensym16_ = NIM_NIL;
		auto T8_ = getCurrentException();
		errX60gensym16_ = ((tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA*) (T8_));
		eqcopy___system_u2609((*(&result)), (*errX60gensym16_).message);
		eqdestroy___pkgZjson95serializationZreader95desc_u113(errX60gensym16_);
		popCurrentException();
	}
	else throw;
	}
	return result;
}
