/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@sstrutils.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@spure@sstrutils.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2372)(NimStringV2& s_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1631)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2& s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s_p0.p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*s_p0.p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
{		nimPrepareStrMutationImpl__system_u2372((*(&s_p0)));
}	}
LA5_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1) {
	NimStringV2 result;
	result = mnewString(count_p1);
	{
		NI i;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(count_p1, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); 		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
		NI res = ((NI)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
				if (!(res <= colontmp_)) goto LA3;
				i = ((NI) (res));
				if (i < 0 || i >= result.len){ raiseIndexError2(i,result.len-1); 				}
				nimPrepareStrMutationV2(result);
				result.p->data[i] = c_p0;
				if (nimAddInt(res, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); 				};
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
{		result = "";
}	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI T1_;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	T1_ = (NI)0;
	{
		if (!(last_p3 < ((NI)0))) goto LA4_;
{		colontmpD_ = (s_p0.len-1);
		T1_ = colontmpD_;
}	}
	goto LA2_;
LA4_: ;
	{
		colontmpD__2 = last_p3;
		T1_ = colontmpD__2;
	}
LA2_: ;
	NI last_2 = T1_;
	if (nimSubInt(last_2, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); 	};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5), ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); 	};
	NI length = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
	{
		if (!(((NI)0) < length)) goto LA9_;
{		if (start_p2 < 0 || start_p2 >= s_p0.len){ raiseIndexError2(start_p2,s_p0.len-1); 		}
		auto T11_ = memchr(((void*) ((&s_p0.p->data[start_p2]))), sub_p1, ((size_t) (length)));
		void* found = T11_;
		{
			if (!!((found == 0))) goto LA14_;
{			result = minuspercent___system_u807(((NI) (ptrdiff_t) (found)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
}		}
LA14_: ;
}	}
LA9_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI T1_;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	T1_ = (NI)0;
	{
		if (!(last_p4 < ((NI)0))) goto LA4_;
{		colontmpD_ = (s_p1.len-1);
		T1_ = colontmpD_;
}	}
	goto LA2_;
LA4_: ;
	{
		colontmpD__2 = last_p4;
		T1_ = colontmpD__2;
	}
LA2_: ;
	NI last_2 = T1_;
	if (nimSubInt(sub_p2.len, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); 	};
	NI subLast = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
	{
		if (!(subLast == ((NI)-1))) goto LA9_;
{		result = start_p3;
		goto BeforeRet_;
}	}
LA9_: ;
	result = ((NI)-1);
	NI skip = start_p3;
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
			if (nimSubInt(last_2, skip, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); 			};
			if (!(subLast <= (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8))) goto LA12;
			NI i = subLast;
			{
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
					if (nimAddInt(skip, i, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); 					};
					if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9),s_p1.len-1); 					}
					if (i < 0 || i >= sub_p2.len){ raiseIndexError2(i,sub_p2.len-1); 					}
					if (!((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)]) == (NU8)(sub_p2.p->data[i]))) goto LA14;
					{
						if (!(i == ((NI)0))) goto LA17_;
{						result = skip;
						goto BeforeRet_;
}					}
LA17_: ;
					if (nimSubInt(i, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); 					};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10);
				} LA14: ;
			}
			if (nimAddInt(skip, subLast, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); 			};
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11) >= s_p1.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11),s_p1.len-1); 			}
			if (nimAddInt(skip, a_p0[(((NU8)(s_p1.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)])))- 0], &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); 			};
			if (TM__JGc9b9bh2D3nTdUR7TGyq8aA_12 < 0 || TM__JGc9b9bh2D3nTdUR7TGyq8aA_12 > IL64(9223372036854775807)){ raiseOverflow(); 			}
			skip = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
		} LA12: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m = sub_p1.len;
	fill__pureZstrutils_u1631(a_p0, 256, m);
	{
		NI i;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(m, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); 		};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
		NI i_2 = ((NI)0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				if (i < 0 || i >= sub_p1.len){ raiseIndexError2(i,sub_p1.len-1); 				}
				if (nimSubInt(m, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); 				};
				if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14), i, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); 				};
				a_p0[(((NU8)(sub_p1.p->data[i])))- 0] = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
				if (nimAddInt(i_2, ((NI)1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); 				};
				i_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
	nsuInitSkipTable(Result, sub_p0);
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T9_;
{	result = (NI)0;
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
		if (nimSubInt(s_p0.len, start_p2, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); 		};
		if (!((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4) < sub_p1.len)) goto LA3_;
{		result = ((NI)-1);
		goto BeforeRet_;
}	}
LA3_: ;
	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
{		if (((NI)0) < 0 || ((NI)0) >= sub_p1.len){ raiseIndexError2(((NI)0),sub_p1.len-1); 		}
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		goto BeforeRet_;
}	}
LA7_: ;
	nimZeroMem((void*)T9_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
	nsuInitNewSkipTable(sub_p1, T9_);
	result = nsuFindStrA(T9_, s_p0, sub_p1, start_p2, last_p3);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1887)(NimStringV2 s_p0, NimStringV2 sub_p1) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	auto T1_ = nsuFindStr(s_p0, sub_p1, ((NI)0), ((NI)-1));
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
