/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sserialization-0.2.2-8cd7d369b8e128106c1978b5bae42fe56689d880@sserialization@serrors.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sserialization-0.2.2-8cd7d369b8e128106c1978b5bae42fe56689d880@sserialization@serrors.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZserializationZerrors_u4)(tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ* err_p0, NimStringV2 filename_p1);
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__ghGsvk7HcJIbtRicfXbnkQ_2 = { 37 | NIM_STRLIT_FLAG, "Serialisation error while processing " };
static const NimStringV2 TM__ghGsvk7HcJIbtRicfXbnkQ_3 = {37, (NimStrPayload*)&TM__ghGsvk7HcJIbtRicfXbnkQ_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__ghGsvk7HcJIbtRicfXbnkQ_6 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__ghGsvk7HcJIbtRicfXbnkQ_7 = {1, (NimStrPayload*)&TM__ghGsvk7HcJIbtRicfXbnkQ_6};
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	auto T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1) {
	{
		NI TM__ghGsvk7HcJIbtRicfXbnkQ_4;
		NI TM__ghGsvk7HcJIbtRicfXbnkQ_5;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
{		if (nimAddInt(src_p1.len, ((NI)1), &TM__ghGsvk7HcJIbtRicfXbnkQ_4)) { raiseOverflow(); 		};
		if (((NI)(TM__ghGsvk7HcJIbtRicfXbnkQ_4)) < ((NI)0) || ((NI)(TM__ghGsvk7HcJIbtRicfXbnkQ_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__ghGsvk7HcJIbtRicfXbnkQ_4), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1726(((void*) ((&(*dest_p0.p).data[dest_p0.len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(TM__ghGsvk7HcJIbtRicfXbnkQ_4)));
		if (nimAddInt(dest_p0.len, src_p1.len, &TM__ghGsvk7HcJIbtRicfXbnkQ_5)) { raiseOverflow(); 		};
		dest_p0.len = (NI)(TM__ghGsvk7HcJIbtRicfXbnkQ_5);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZserializationZerrors_u4)(tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = rawNewString(filename_p1.len + (*err_p0).message.len + 38);
appendString(T1_, TM__ghGsvk7HcJIbtRicfXbnkQ_3);
appendString(T1_, filename_p1);
appendString(T1_, TM__ghGsvk7HcJIbtRicfXbnkQ_7);
appendString(T1_, (*err_p0).message);
	result = T1_;
	return result;
}
