/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@sstd@ssyncio.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s..@s..@sopt@shomebrew@sCellar@snim@s2.2.0@snim@slib@sstd@ssyncio.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <stdio.h>
#include <exception>
#include <string.h>
#include <errno.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
typedef NU8 tyEnum_FileSeekPos__2a62RUrgE0p4vRcDhcz9aNA;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u144)(FILE* f_p0);
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u91)(NimStringV2 msg_p0) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2606)(NimStringV2& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2 = { 7 | NIM_STRLIT_FLAG, "errno: " };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3 = {7, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_2};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6 = { 2 | NIM_STRLIT_FLAG, " `" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7 = {2, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8 = { 1 | NIM_STRLIT_FLAG, "`" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9 = {1, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_8};
extern TNimTypeV2 NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_;
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10 = { 29 | NIM_STRLIT_FLAG, "cannot retrieve file position" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11 = {29, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_10};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12 = { 24 | NIM_STRLIT_FLAG, "cannot set file position" };
static const NimStringV2 TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13 = {24, (NimStrPayload*)&TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_12};
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	auto T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2& dest_p0, NimStringV2 src_p1) {
	{
		NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4;
		NI TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
{		if (nimAddInt(src_p1.len, ((NI)1), &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)) { raiseOverflow(); 		};
		if (((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)) < ((NI)0) || ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1726(((void*) ((&(*dest_p0.p).data[dest_p0.len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), ((NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_4)));
		if (nimAddInt(dest_p0.len, src_p1.len, &TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5)) { raiseOverflow(); 		};
		dest_p0.len = (NI)(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_5);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseEIO__stdZsyncio_u91)(NimStringV2 msg_p0) {
	std::exception_ptr T2_;
	tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ* T3_;
	NimStringV2 blitTmp;
	try {
	T3_ = NIM_NIL;
	T3_ = (tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ*) nimNewObj(sizeof(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ), NIM_ALIGNOF(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ));
	(*T3_).m_type = (&NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_);
	(*T3_).name = "IOError";
	blitTmp = msg_p0;
	eqwasMoved___system_u2606((*(&msg_p0)));
	(*T3_).message = blitTmp;
	(*T3_).parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T3_, "IOError", "raiseEIO", "syncio.nim", 155);
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		if (msg_p0.p && !(msg_p0.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg_p0.p);
}
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, checkErr__stdZsyncio_u144)(FILE* f_p0) {
	{
		NimStringV2 msg;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		std::exception_ptr T7_;
		NimStringV2 T8_;
		NimStringV2 blitTmp;
		auto T3_ = ferror(f_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
{		msg.len = 0; msg.p = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		try {
		T8_.len = 0; T8_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u8(((NI) (errno)));
		auto T9_ = strerror(errno);
		colontmpD__2 = cstrToNimstr((NCSTRING) T9_);
		T8_ = rawNewString(colontmpD_.len + colontmpD__2.len + 10);
appendString(T8_, TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_3);
appendString(T8_, colontmpD_);
appendString(T8_, TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_7);
appendString(T8_, colontmpD__2);
appendString(T8_, TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_9);
		msg = T8_;
		clearerr(f_p0);
		blitTmp = msg;
		eqwasMoved___system_u2606((*(&msg)));
		raiseEIO__stdZsyncio_u91(blitTmp);
		}
		catch (Exception* T8_) {
		T7_ = std::current_exception();
		}
		catch (...) {
			T7_ = std::current_exception();
		}
		{
			if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (msg.p && !(msg.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(msg.p);
}
			if (T7_) std::rethrow_exception(T7_);
		}
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBuffer__stdZsyncio_u147)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	auto T1_ = fread(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	{
		if (!!((result == len_p2))) goto LA4_;
{		checkErr__stdZsyncio_u144(f_p0);
}	}
LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, getFilePos__stdZsyncio_u484)(FILE* f_p0) {
	NI64 result;
	result = ftello(f_p0);
	{
		if (!(result < IL64(0))) goto LA3_;
{		raiseEIO__stdZsyncio_u91(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_11);
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setFilePos__stdZsyncio_u464)(FILE* f_p0, NI64 pos_p1, tyEnum_FileSeekPos__2a62RUrgE0p4vRcDhcz9aNA relativeTo_p2) {
	{
		auto T3_ = fseeko(f_p0, pos_p1, ((int) (relativeTo_p2)));
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
{		raiseEIO__stdZsyncio_u91(TM__xNF6mvRQ4Pd1hTNM9cEHXwQ_13);
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u243)(FILE* f_p0) {
	{
		if (!!((f_p0 == 0))) goto LA3_;
{		auto T5_ = fclose(f_p0);
		(void)(T5_);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u178)(FILE* f_p0, void* buffer_p1, NI len_p2) {
	NI result;
	auto T1_ = fwrite(buffer_p1, ((size_t)1), ((size_t) (len_p2)), f_p0);
	result = ((NI) (T1_));
	checkErr__stdZsyncio_u144(f_p0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u252)(FILE* f_p0) {
	auto T1_ = fflush(f_p0);
	(void)(T1_);
}
