/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sfaststreams-0.3.0-537acd856f131772e5553318f53bf1263935034a@sfaststreams@soutputs.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sfaststreams-0.3.0-537acd856f131772e5553318f53bf1263935034a@sfaststreams@soutputs.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <exception>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ;
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA;
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg;
struct RootObj;
struct TNimTypeV2;
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w;
struct tyObject_FileOutputStreamcolonObjectType___Lu1mPzcPJcNVWcY9c2nz1Ig;
struct tyObject_Deque__du7hawUjwrOv3acirvjaug;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g;
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content;
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ;
struct NimStrPayload;
struct NimStringV2;
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA;
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w;
struct Exception;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
typedef N_NIMCALL_PTR(void, tyProc__MQ9cSkryDfvHRyqOUsINC4g) (tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, void* src_p1, NI srcLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__Ttxw6DLJAiKTJgoTQyz1og) (tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
struct tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ {
	tyProc__MQ9cSkryDfvHRyqOUsINC4g writeSync;
	tyProc__Ttxw6DLJAiKTJgoTQyz1og flushSync;
	tyProc__Ttxw6DLJAiKTJgoTQyz1og closeSync;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w {
	NU8* startAddr;
	NU8* endAddr;
};
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA : public RootObj {
	tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ* vtable;
	tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers;
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w span;
	NI spanEndPos;
	NI extCursorsCount;
};
struct tyObject_FileOutputStreamcolonObjectType___Lu1mPzcPJcNVWcY9c2nz1Ig : public tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA {
	FILE* file;
	NIM_BOOL allowAsyncOps;
};
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g {
  NI len; tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content* p;
};
struct tyObject_Deque__du7hawUjwrOv3acirvjaug {
	tySequence__a5J6HCFyQ89bjZwQcmZVP4g data;
	NU head;
	NU tail;
};
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg {
	NI pageSize;
	NI maxBufferedBytes;
	tyObject_Deque__du7hawUjwrOv3acirvjaug queue;
	NIM_BOOL eofReached;
	NI fauxEofPos;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w : public Exception {
};
struct tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA : public tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w {
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ {
	NI consumedTo;
	NI writtenTo;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* data;
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
struct tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s;
};
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct tySequence__a5J6HCFyQ89bjZwQcmZVP4g_Content { NI cap; tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, writeFileSync__pkgZfaststreamsZoutputs_u256)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, void* src_p1, NI srcLen_p2);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u203)(NimStringV2 msg_p0);
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZbuffers_u248)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1);
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, peekFirst__pkgZfaststreamsZbuffers_u1140)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(NU8*, readableStart__pkgZfaststreamsZbuffers_u59)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, writeBuffer__stdZsyncio_u178)(FILE* f_p0, void* buffer_p1, NI len_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pkgZfaststreamsZbuffers_u254)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZbuffers_u242)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*& dest_p0);
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, popFirst__pkgZfaststreamsZbuffers_u214)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u245)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, addLast__pkgZfaststreamsZbuffers_u728)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0, tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* item_p1);
N_LIB_PRIVATE N_NIMCALL(void, flushFileSync__pkgZfaststreamsZoutputs_u334)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, flushFile__stdZsyncio_u252)(FILE* f_p0);
N_LIB_PRIVATE N_NIMCALL(void, closeFileSync__pkgZfaststreamsZoutputs_u336)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__stdZsyncio_u243)(FILE* f_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZfaststreamsZoutputs_u1455)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u141)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA& dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZbuffers_u400)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*, initPageBuffers__pkgZfaststreamsZbuffers_u393)(NI pageSize_p0, NI maxBufferedBytes_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZoutputs_u129)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*& dest_p0, tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, addPage__pkgZfaststreamsZoutputs_u173)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, addWritablePage__pkgZfaststreamsZbuffers_u655)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI pageSize_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w, fullSpan__pkgZfaststreamsZbuffers_u377)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0);
N_LIB_PRIVATE N_NIMCALL(void, trackWrittenToEnd__pkgZfaststreamsZbuffers_u568)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0);
N_LIB_PRIVATE N_NIMCALL(void, drainAllBuffersSync__pkgZfaststreamsZoutputs_u485)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, void* buf_p1, NI bufSize_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, getWritablePage__pkgZfaststreamsZbuffers_u878)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NI preferredSize_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w, writableSpan__pkgZfaststreamsZbuffers_u355)(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_p0);
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NU8*, baseAddr__pkgZfaststreamsZbuffers_u62)(NU8* x_p0, NI x_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, writeToANewPage__pkgZfaststreamsZoutputs_u875)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8* bytes_p1, NI bytes_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nextAlignedSize__pkgZfaststreamsZbuffers_u930)(NI minSize_p0, NI pageSize_p1);
N_LIB_PRIVATE N_NIMCALL(void, trackWrittenTo__pkgZfaststreamsZbuffers_u611)(tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers_p0, NU8* spanHeadPos_p1);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NI, pos__pkgZfaststreamsZoutputs_u354)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, add__pkgZstewZstrings_u1)(NimStringV2& s_p0, NIM_CHAR* data_p1, NI data_p1Len_0);
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_2 = { 37 | NIM_STRLIT_FLAG, "buffers.nim(286, 3) `buffers != nil` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_3 = {37, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_2};
extern TNimTypeV2 NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_;
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_4 = { 12 | NIM_STRLIT_FLAG, "Empty deque." };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_5 = {12, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_4};
extern TNimTypeV2 NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_;
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_7 = { 33 | NIM_STRLIT_FLAG, "Failed to write all bytes to FILE" };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_8 = {33, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_7};
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_9 = {12, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_4};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_10 = { 44 | NIM_STRLIT_FLAG, "outputs.nim(253, 5) `writeStartAddr != nil` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_11 = {44, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_10};
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_12 = {33, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_7};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_13 = { 35 | NIM_STRLIT_FLAG, "outputs.nim(203, 3) `pageSize > 0` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_14 = {35, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_13};
N_LIB_PRIVATE TNimTypeV2 NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_;
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_18 = { 38 | NIM_STRLIT_FLAG, "outputs.nim(581, 5) `s.vtable != nil` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_19 = {38, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_18};
static const struct {
  NI cap; NIM_CHAR data[48+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_20 = { 48 | NIM_STRLIT_FLAG, "outputs.nim(583, 5) `s.vtable.writeSync != nil` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_21 = {48, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_20};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_25 = { 39 | NIM_STRLIT_FLAG, "outputs.nim(650, 3) `s.buffers != nil` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_26 = {39, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_25};
static const struct {
  NI cap; NIM_CHAR data[74+1];
} TM__M8fx9bXu9bLHGnuCFOJXouvA_28 = { 74 | NIM_STRLIT_FLAG, "outputs.nim(914, 3) `s.extCursorsCount == 0 and\012  not (s.buffers == nil)` " };
static const NimStringV2 TM__M8fx9bXu9bLHGnuCFOJXouvA_29 = {74, (NimStrPayload*)&TM__M8fx9bXu9bLHGnuCFOJXouvA_28};
N_LIB_PRIVATE tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ fileOutputVTable__pkgZfaststreamsZoutputs_u338;
static NU32 TM__M8fx9bXu9bLHGnuCFOJXouvA_16[2] = {3701606400, 206372608};
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(NI, len__pkgZfaststreamsZbuffers_u124)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NI result;
	result = (NI)0;
	if ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head)) > (NU)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); 	}
	result = ((NI) ((NU)((NU64)((*deq_p0).tail) - (NU64)((*deq_p0).head))));
	return result;
}
static N_INLINE(NU, mask__pkgZfaststreamsZbuffers_u175)(tyObject_Deque__du7hawUjwrOv3acirvjaug* deq_p0) {
	NU result;
	NI T1_;
	T1_ = (*deq_p0).data.len;
	result = (NU)((NU64)(((NU) (T1_))) - (NU64)(((NU)1)));
	return result;
}
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**, peekFirst__pkgZfaststreamsZbuffers_u1140)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ** result;
	result = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**)0;
	{
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T6_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T3_ < ((NI)1)))) goto LA4_;
{		T6_ = NIM_NIL;
		T6_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T6_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T6_).name = "IndexDefect";
		(*T6_).message = TM__M8fx9bXu9bLHGnuCFOJXouvA_5;
		(*T6_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IndexDefect", "peekFirst", "deques.nim", 105);
}	}
LA4_: ;
	auto T7_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)(deq_p0.head & T7_) < 0 || (NU)(deq_p0.head & T7_) >= deq_p0.data.len){ raiseIndexError2((NU)(deq_p0.head & T7_),deq_p0.data.len-1); 	}
	result = &deq_p0.data.p->data[(NU)(deq_p0.head & T7_)];
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*, popFirst__pkgZfaststreamsZbuffers_u214)(tyObject_Deque__du7hawUjwrOv3acirvjaug& deq_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* result;
	result = NIM_NIL;
	{
		tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA* T6_;
		auto T3_ = len__pkgZfaststreamsZbuffers_u124((&deq_p0));
		if (!NIM_UNLIKELY((T3_ < ((NI)1)))) goto LA4_;
{		T6_ = NIM_NIL;
		T6_ = (tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA*) nimNewObj(sizeof(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA), NIM_ALIGNOF(tyObject_IndexDefect__nDMr65l8eP9cDx1d9ckVaCDA));
		(*T6_).m_type = (&NTIv2__nDMr65l8eP9cDx1d9ckVaCDA_);
		(*T6_).name = "IndexDefect";
		(*T6_).message = TM__M8fx9bXu9bLHGnuCFOJXouvA_9;
		(*T6_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T6_, "IndexDefect", "popFirst", "deques.nim", 105);
}	}
LA4_: ;
	auto T7_ = mask__pkgZfaststreamsZbuffers_u175((&deq_p0));
	if ((NU)(deq_p0.head & T7_) < 0 || (NU)(deq_p0.head & T7_) >= deq_p0.data.len){ raiseIndexError2((NU)(deq_p0.head & T7_),deq_p0.data.len-1); 	}
	result = deq_p0.data.p->data[(NU)(deq_p0.head & T7_)];
	eqwasMoved___pkgZfaststreamsZbuffers_u242(deq_p0.data.p->data[(NU)(deq_p0.head & T7_)]);
	deq_p0.head += ((NI)1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeFileSync__pkgZfaststreamsZoutputs_u256)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, void* src_p1, NI srcLen_p2) {
	tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffersX60gensym37_;
	buffersX60gensym37_ = NIM_NIL;
	if (s_p0 && !isObjDisplayCheck((*s_p0).m_type, 2, 3982900992)){ raiseObjectConversionError(); 	}
	FILE* file = (*((tyObject_FileOutputStreamcolonObjectType___Lu1mPzcPJcNVWcY9c2nz1Ig*) (s_p0))).file;
	buffersX60gensym37_ = (*s_p0).buffers;
	void* writeStartAddr = src_p1;
	NI writeLen = srcLen_p2;
	{
		if (!!((buffersX60gensym37_ == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL)))) goto LA3_;
{		{
			NU8* writeStartAddr_2;
			NI writeLen_2;
			writeStartAddr_2 = (NU8*)0;
			writeLen_2 = (NI)0;
			{
				tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page;
				tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* recycledPage;
				std::exception_ptr T8_;
				page = NIM_NIL;
				recycledPage = NIM_NIL;
				try {
				{
					if (!!(!(((*s_p0).buffers == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL))))) goto LA11_;
{					failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_3);
}				}
LA11_: ;
				{
					while (1) {
						tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* page_2;
						tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* colontmpD_;
						std::exception_ptr T17_;
						NI TM__M8fx9bXu9bLHGnuCFOJXouvA_6;
						auto T15_ = len__pkgZfaststreamsZbuffers_u124((&(*(*s_p0).buffers).queue));
						if (!(((NI)0) < T15_)) goto LA14;
						page_2 = NIM_NIL;
						colontmpD_ = NIM_NIL;
						try {
						auto T18_ = peekFirst__pkgZfaststreamsZbuffers_u1140((*(&(*(*s_p0).buffers).queue)));
						eqcopy___pkgZfaststreamsZbuffers_u248((*&page_2), (*T18_));
						page = page_2;
						writeStartAddr_2 = readableStart__pkgZfaststreamsZbuffers_u59(page);
						if (nimSubInt((*page).writtenTo, (*page).consumedTo, &TM__M8fx9bXu9bLHGnuCFOJXouvA_6)) { raiseOverflow(); 						};
						if (((NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_6)) < ((NI)0) || ((NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_6)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_6), ((NI)0), ((NI)IL64(9223372036854775807))); 						}
						writeLen_2 = ((NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_6));
						auto T19_ = writeBuffer__stdZsyncio_u178(file, ((void*) (writeStartAddr_2)), writeLen_2);
						NI bytesWrittenX60gensym37_ = T19_;
						{
							tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ* T24_;
							if (!!((bytesWrittenX60gensym37_ == writeLen_2))) goto LA22_;
{							T24_ = NIM_NIL;
							T24_ = (tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ*) nimNewObj(sizeof(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ), NIM_ALIGNOF(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ));
							(*T24_).m_type = (&NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_);
							(*T24_).name = "IOError";
							(*T24_).message = TM__M8fx9bXu9bLHGnuCFOJXouvA_8;
							(*T24_).parent = ((Exception*) NIM_NIL);
							raiseExceptionEx((Exception*)T24_, "IOError", "writeFileSync", "outputs.nim", 250);
}						}
LA22_: ;
						{
							NI T27_;
							T27_ = (*(*page_2).data).len;
							if (!(T27_ == (*(*s_p0).buffers).pageSize)) goto LA28_;
{							eqsink___pkgZfaststreamsZbuffers_u254((*&recycledPage), page_2);
							eqwasMoved___pkgZfaststreamsZbuffers_u242((*&page_2));
}						}
LA28_: ;
						colontmpD_ = popFirst__pkgZfaststreamsZbuffers_u214((*(&(*(*s_p0).buffers).queue)));
						(void)(colontmpD_);
						}
						catch (Exception* T18_) {
						T17_ = std::current_exception();
						}
						catch (...) {
							T17_ = std::current_exception();
						}
						{
							eqdestroy___pkgZfaststreamsZbuffers_u245(colontmpD_);
							eqdestroy___pkgZfaststreamsZbuffers_u245(page_2);
							if (T17_) std::rethrow_exception(T17_);
						}
					} LA14: ;
				}
				{
					if (!!((recycledPage == ((tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ*) NIM_NIL)))) goto LA34_;
{					(*recycledPage).consumedTo = ((NI)0);
					(*recycledPage).writtenTo = ((NI)0);
					tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* blitTmp = recycledPage;
					eqwasMoved___pkgZfaststreamsZbuffers_u242((*&recycledPage));
					addLast__pkgZfaststreamsZbuffers_u728((*(&(*(*s_p0).buffers).queue)), blitTmp);
}				}
LA34_: ;
				}
				catch (Exception* T9_) {
				T8_ = std::current_exception();
				}
				catch (...) {
					T8_ = std::current_exception();
				}
				{
					eqdestroy___pkgZfaststreamsZbuffers_u245(recycledPage);
					if (T8_) std::rethrow_exception(T8_);
				}
			}
		}
}	}
LA3_: ;
	{
		if (!(((NI)0) < writeLen)) goto LA40_;
{		{
			if (!!(!((writeStartAddr == NIM_NIL)))) goto LA44_;
{			failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_11);
}		}
LA44_: ;
		auto T46_ = writeBuffer__stdZsyncio_u178(file, writeStartAddr, writeLen);
		NI bytesWrittenX60gensym37__2 = T46_;
		{
			tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ* T51_;
			if (!!((bytesWrittenX60gensym37__2 == writeLen))) goto LA49_;
{			T51_ = NIM_NIL;
			T51_ = (tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ*) nimNewObj(sizeof(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ), NIM_ALIGNOF(tyObject_IOError__ghYkvq4nTOT0MFeg0oBOYQ));
			(*T51_).m_type = (&NTIv2__ghYkvq4nTOT0MFeg0oBOYQ_);
			(*T51_).name = "IOError";
			(*T51_).message = TM__M8fx9bXu9bLHGnuCFOJXouvA_12;
			(*T51_).parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T51_, "IOError", "writeFileSync", "outputs.nim", 255);
}		}
LA49_: ;
}	}
LA40_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, flushFileSync__pkgZfaststreamsZoutputs_u334)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0) {
	if (s_p0 && !isObjDisplayCheck((*s_p0).m_type, 2, 3982900992)){ raiseObjectConversionError(); 	}
	flushFile__stdZsyncio_u252((*((tyObject_FileOutputStreamcolonObjectType___Lu1mPzcPJcNVWcY9c2nz1Ig*) (s_p0))).file);
}
N_LIB_PRIVATE N_NIMCALL(void, closeFileSync__pkgZfaststreamsZoutputs_u336)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0) {
	if (s_p0 && !isObjDisplayCheck((*s_p0).m_type, 2, 3982900992)){ raiseObjectConversionError(); 	}
	close__stdZsyncio_u243((*((tyObject_FileOutputStreamcolonObjectType___Lu1mPzcPJcNVWcY9c2nz1Ig*) (s_p0))).file);
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__M8fx9bXu9bLHGnuCFOJXouvA_15;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__M8fx9bXu9bLHGnuCFOJXouvA_15)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_15);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u141)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.buffers);
		if (!T3_) goto LA4_;
{		eqdestroy___pkgZfaststreamsZbuffers_u400((*dest_p0.buffers));
		nimRawDispose(dest_p0.buffers, ((NI)8));
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pkgZfaststreamsZoutputs_u1455)(void* dest_p0) {
	eqdestroy___pkgZfaststreamsZoutputs_u141((*(&(*((tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*) (dest_p0))))));
}
N_LIB_PRIVATE N_NIMCALL(void, memoryOutput__pkgZfaststreamsZoutputs_u184)(NI pageSize_p0, tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw* Result) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym22_;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* T5_;
	nimZeroMem((void*)Result, sizeof(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw));
	sX60gensym22_ = NIM_NIL;
	{
		if (!!((((NI)0) < pageSize_p0))) goto LA3_;
{		failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_14);
}	}
LA3_: ;
	T5_ = NIM_NIL;
	T5_ = (tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*) nimNewObj(sizeof(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA), NIM_ALIGNOF(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA));
	(*T5_).m_type = (&NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_);
	if ((pageSize_p0) < ((NI)0) || (pageSize_p0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pageSize_p0, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	(*T5_).buffers = initPageBuffers__pkgZfaststreamsZbuffers_u393((pageSize_p0), ((NI)0));
	sX60gensym22_ = T5_;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* blitTmp = sX60gensym22_;
	(*Result).s = blitTmp;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI TM__M8fx9bXu9bLHGnuCFOJXouvA_17;
	auto T1_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
	if (nimAddInt((*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc, ((NI)8), &TM__M8fx9bXu9bLHGnuCFOJXouvA_17)) { raiseOverflow(); 	};
	(*((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T1_))).rc = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_17);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*, eqdup___pkgZfaststreamsZoutputs_u132)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* src_p0) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
{		nimIncRef(src_p0);
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZoutputs_u129)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*& dest_p0, tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* src_p1) {
	{
		if (!src_p1) goto LA3_;
{		nimIncRef(src_p1);
}	}
LA3_: ;
	{
		auto T7_ = nimDecRefIsLast(dest_p0);
		if (!T7_) goto LA8_;
{		nimDestroyAndDispose(dest_p0);
}	}
LA8_: ;
	dest_p0 = src_p1;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*, implicitDeref__pkgZfaststreamsZoutputs_u120)(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw h_p0) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* result;
	result = NIM_NIL;
	eqcopy___pkgZfaststreamsZoutputs_u129((*&result), h_p0.s);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addPage__pkgZfaststreamsZoutputs_u173)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* nextPage;
	NI TM__M8fx9bXu9bLHGnuCFOJXouvA_22;
	nextPage = NIM_NIL;
	NI nextPageSize = (*(*s_p0).buffers).pageSize;
	nextPage = addWritablePage__pkgZfaststreamsZbuffers_u655((*s_p0).buffers, nextPageSize);
	(*s_p0).span = fullSpan__pkgZfaststreamsZbuffers_u377(nextPage);
	if (nimAddInt((*s_p0).spanEndPos, nextPageSize, &TM__M8fx9bXu9bLHGnuCFOJXouvA_22)) { raiseOverflow(); 	};
	if (TM__M8fx9bXu9bLHGnuCFOJXouvA_22 < 0 || TM__M8fx9bXu9bLHGnuCFOJXouvA_22 > IL64(9223372036854775807)){ raiseOverflow(); 	}
	(*s_p0).spanEndPos = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_22);
	eqdestroy___pkgZfaststreamsZbuffers_u245(nextPage);
}
N_LIB_PRIVATE N_NIMCALL(void, drainAllBuffersSync__pkgZfaststreamsZoutputs_u485)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, void* buf_p1, NI bufSize_p2) {
	(*(*s_p0).vtable).writeSync(s_p0, buf_p1, bufSize_p2);
	{
		tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* pageX60gensym66_;
		NI TM__M8fx9bXu9bLHGnuCFOJXouvA_23;
		if (!!(((*s_p0).buffers == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL)))) goto LA3_;
{		pageX60gensym66_ = NIM_NIL;
		pageX60gensym66_ = getWritablePage__pkgZfaststreamsZbuffers_u878((*s_p0).buffers, (*(*s_p0).buffers).pageSize);
		(*s_p0).span = writableSpan__pkgZfaststreamsZbuffers_u355(pageX60gensym66_);
		if (((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) < ((NI)0) || ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))), ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		if (nimAddInt((*s_p0).spanEndPos, ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))), &TM__M8fx9bXu9bLHGnuCFOJXouvA_23)) { raiseOverflow(); 		};
		if (TM__M8fx9bXu9bLHGnuCFOJXouvA_23 < 0 || TM__M8fx9bXu9bLHGnuCFOJXouvA_23 > IL64(9223372036854775807)){ raiseOverflow(); 		}
		(*s_p0).spanEndPos = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_23);
		eqdestroy___pkgZfaststreamsZbuffers_u245(pageX60gensym66_);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeToNewSpan__pkgZfaststreamsZoutputs_u825)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8 b_p1) {
	{
		if (!((*s_p0).buffers == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL))) goto LA3_;
{		{
			if (!!(!(((*s_p0).vtable == ((tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ*) NIM_NIL))))) goto LA7_;
{			failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_19);
}		}
LA7_: ;
		{
			if (!!(!(((*(*s_p0).vtable).writeSync == NIM_NIL)))) goto LA11_;
{			failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_21);
}		}
LA11_: ;
		(*(*s_p0).vtable).writeSync(s_p0, ((void*) ((&b_p1))), ((NI)1));
}	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		T14_ = ((*s_p0).vtable == ((tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ*) NIM_NIL));
		if (T14_) goto LA15_;
		T14_ = (((NI)0) < (*s_p0).extCursorsCount);
LA15_: ;
		if (!T14_) goto LA16_;
{		addPage__pkgZfaststreamsZoutputs_u173(s_p0);
		(*(*s_p0).span.startAddr) = b_p1;
		NU bytesX60gensym131_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*s_p0).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym131_))))))))));
}	}
	goto LA1_;
LA16_: ;
	{
		trackWrittenToEnd__pkgZfaststreamsZbuffers_u568((*s_p0).buffers);
		drainAllBuffersSync__pkgZfaststreamsZoutputs_u485(s_p0, NIM_NIL, ((NI)0));
		(*(*s_p0).span.startAddr) = b_p1;
		NU bytesX60gensym135_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*s_p0).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym135_))))))))));
	}
LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u126)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0);
}	}
LA4_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	auto T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1726)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToANewPage__pkgZfaststreamsZoutputs_u875)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8* bytes_p1, NI bytes_p1Len_0) {
	tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ* nextPage;
	NI TM__M8fx9bXu9bLHGnuCFOJXouvA_27;
	nextPage = NIM_NIL;
	if (((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) < ((NI)0) || ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	NI runway = ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))));
	auto T1_ = baseAddr__pkgZfaststreamsZbuffers_u62(bytes_p1, bytes_p1Len_0);
	NU8* inputPos = T1_;
	NI inputLen = bytes_p1Len_0;
	{
		NI TM__M8fx9bXu9bLHGnuCFOJXouvA_24;
		if (!(((NI)0) < runway)) goto LA4_;
{		copyMem__system_u1726(((void*) ((*s_p0).span.startAddr)), ((void*) (inputPos)), runway);
		NU bytesX60gensym142_ = (NU)((NU64)(((NU) (runway))) * (NU64)(((NU)1)));
		inputPos = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) (inputPos))))) + (NU64)(((NU) (((NI) (bytesX60gensym142_))))))))));
		if (nimSubInt(inputLen, runway, &TM__M8fx9bXu9bLHGnuCFOJXouvA_24)) { raiseOverflow(); 		};
		inputLen = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_24);
}	}
LA4_: ;
	{
		if (!!(!(((*s_p0).buffers == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL))))) goto LA8_;
{		failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_26);
}	}
LA8_: ;
	if ((inputLen) < ((NI)0) || (inputLen) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(inputLen, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	auto T10_ = nextAlignedSize__pkgZfaststreamsZbuffers_u930((inputLen), (*(*s_p0).buffers).pageSize);
	NI nextPageSize = T10_;
	nextPage = addWritablePage__pkgZfaststreamsZbuffers_u655((*s_p0).buffers, nextPageSize);
	(*s_p0).span = fullSpan__pkgZfaststreamsZbuffers_u377(nextPage);
	if (nimAddInt((*s_p0).spanEndPos, nextPageSize, &TM__M8fx9bXu9bLHGnuCFOJXouvA_27)) { raiseOverflow(); 	};
	if (TM__M8fx9bXu9bLHGnuCFOJXouvA_27 < 0 || TM__M8fx9bXu9bLHGnuCFOJXouvA_27 > IL64(9223372036854775807)){ raiseOverflow(); 	}
	(*s_p0).spanEndPos = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_27);
	if ((inputLen) < ((NI)0) || (inputLen) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(inputLen, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	copyMem__system_u1726(((void*) ((*s_p0).span.startAddr)), ((void*) (inputPos)), (inputLen));
	NU bytesX60gensym148_ = (NU)((NU64)(((NU) (inputLen))) * (NU64)(((NU)1)));
	(*s_p0).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym148_))))))))));
	eqdestroy___pkgZfaststreamsZbuffers_u245(nextPage);
}
N_LIB_PRIVATE N_NIMCALL(void, write__pkgZfaststreamsZoutputs_u930)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8* bytes_p1, NI bytes_p1Len_0) {
{	NI inputLenX60gensym150_ = bytes_p1Len_0;
	{
		if (!(inputLenX60gensym150_ == ((NI)0))) goto LA3_;
{		goto BeforeRet_;
}	}
LA3_: ;
	if (((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) < ((NI)0) || ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	NI runwayX60gensym150_ = ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))));
	{
		if (!(inputLenX60gensym150_ <= runwayX60gensym150_)) goto LA7_;
{		auto T9_ = baseAddr__pkgZfaststreamsZbuffers_u62(bytes_p1, bytes_p1Len_0);
		if ((inputLenX60gensym150_) < ((NI)0) || (inputLenX60gensym150_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(inputLenX60gensym150_, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		copyMem__system_u1726(((void*) ((*s_p0).span.startAddr)), ((void*) (T9_)), (inputLenX60gensym150_));
		NU bytesX60gensym154_ = (NU)((NU64)(((NU) (inputLenX60gensym150_))) * (NU64)(((NU)1)));
		(*s_p0).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym154_))))))))));
}	}
	goto LA5_;
LA7_: ;
	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = ((*s_p0).vtable == ((tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ*) NIM_NIL));
		if (T11_) goto LA12_;
		T11_ = (((NI)0) < (*s_p0).extCursorsCount);
LA12_: ;
		if (!T11_) goto LA13_;
{		writeToANewPage__pkgZfaststreamsZoutputs_u875(s_p0, bytes_p1, bytes_p1Len_0);
}	}
	goto LA5_;
LA13_: ;
	{
		trackWrittenTo__pkgZfaststreamsZbuffers_u611((*s_p0).buffers, (*s_p0).span.startAddr);
		auto T16_ = baseAddr__pkgZfaststreamsZbuffers_u62(bytes_p1, bytes_p1Len_0);
		if ((bytes_p1Len_0) < ((NI)0) || (bytes_p1Len_0) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(bytes_p1Len_0, ((NI)0), ((NI)IL64(9223372036854775807))); 		}
		drainAllBuffersSync__pkgZfaststreamsZoutputs_u485(s_p0, ((void*) (T16_)), (bytes_p1Len_0));
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZoutputs_u123)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*& dest_p0) {
	dest_p0 = 0;
}
N_LIB_PRIVATE N_NIMCALL(NI, pos__pkgZfaststreamsZoutputs_u354)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0) {
	NI result;
	NI TM__M8fx9bXu9bLHGnuCFOJXouvA_30;
	result = (NI)0;
	if (((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) < ((NI)0) || ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1))), ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	if (nimSubInt((*s_p0).spanEndPos, ((NI)((((NI) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.endAddr))))) - (NU64)(((NU) (ptrdiff_t) (((void*) ((*s_p0).span.startAddr))))))))) / (((NI)1)))), &TM__M8fx9bXu9bLHGnuCFOJXouvA_30)) { raiseOverflow(); 	};
	result = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_30);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getOutput__businessZdata_u1104)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((*s_p0).extCursorsCount == ((NI)0));
		if (!(T3_)) goto LA4_;
		T3_ = !(((*s_p0).buffers == ((tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg*) NIM_NIL)));
LA4_: ;
		if (!!(T3_)) goto LA5_;
{		failedAssertImpl__stdZassertions_u203(TM__M8fx9bXu9bLHGnuCFOJXouvA_29);
}	}
LA5_: ;
	trackWrittenTo__pkgZfaststreamsZbuffers_u611((*s_p0).buffers, (*s_p0).span.startAddr);
	auto T7_ = pos__pkgZfaststreamsZoutputs_u354(s_p0);
	if ((T7_) < ((NI)0) || (T7_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T7_, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	result = rawNewString((T7_));
	{
		tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ** page;
		page = (tyObject_Page__qdcGjhU7GWLgmfnWUx9c6HQ**)0;
		{
			NI c;
			NI colontmp_;
			c = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = len__pkgZfaststreamsZbuffers_u124((&(*(*s_p0).buffers).queue));
			NI i = ((NI)0);
			{
				while (1) {
					NI TM__M8fx9bXu9bLHGnuCFOJXouvA_31;
					NI TM__M8fx9bXu9bLHGnuCFOJXouvA_32;
					if (!(i < colontmp_)) goto LA11;
					c = i;
					auto T12_ = mask__pkgZfaststreamsZbuffers_u175((&(*(*s_p0).buffers).queue));
					if ((NU)((NU)((NU64)((*(*s_p0).buffers).queue.head) + (NU64)(((NU) (c)))) & T12_) < 0 || (NU)((NU)((NU64)((*(*s_p0).buffers).queue.head) + (NU64)(((NU) (c)))) & T12_) >= (*(*s_p0).buffers).queue.data.len){ raiseIndexError2((NU)((NU)((NU64)((*(*s_p0).buffers).queue.head) + (NU64)(((NU) (c)))) & T12_),(*(*s_p0).buffers).queue.data.len-1); 					}
					page = &(*(*s_p0).buffers).queue.data.p->data[(NU)((NU)((NU64)((*(*s_p0).buffers).queue.head) + (NU64)(((NU) (c)))) & T12_)];
					auto T13_ = baseAddr__pkgZfaststreamsZbuffers_u62((((*(*(*page)).data)).p) ? ((*(*(*page)).data).p->data) : NIM_NIL, (*(*(*page)).data).len);
					NIM_CHAR* baseAddrX60gensym258_ = ((NIM_CHAR*) (T13_));
					if (nimSubInt((*(*page)).writtenTo, ((NI)1), &TM__M8fx9bXu9bLHGnuCFOJXouvA_31)) { raiseOverflow(); 					};
					add__pkgZstewZstrings_u1((*(&result)), (NIM_CHAR*)(baseAddrX60gensym258_)+((*(*page)).consumedTo), ((NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_31))-((*(*page)).consumedTo)+1);
					if (nimAddInt(i, ((NI)1), &TM__M8fx9bXu9bLHGnuCFOJXouvA_32)) { raiseOverflow(); 					};
					i = (NI)(TM__M8fx9bXu9bLHGnuCFOJXouvA_32);
				} LA11: ;
			}
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u197)(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.s);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.s);
}	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_Init000)(void) {
{
	fileOutputVTable__pkgZfaststreamsZoutputs_u338.writeSync = writeFileSync__pkgZfaststreamsZoutputs_u256;
	fileOutputVTable__pkgZfaststreamsZoutputs_u338.flushSync = flushFileSync__pkgZfaststreamsZoutputs_u334;
	fileOutputVTable__pkgZfaststreamsZoutputs_u338.closeSync = closeFileSync__pkgZfaststreamsZoutputs_u336;
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_DatInit000)(void) {
NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.destructor = (void*)rttiDestroy__pkgZfaststreamsZoutputs_u1455; NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.traceImpl = (void*)NIM_NIL; NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.size = sizeof(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA); NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.align = (NI16) NIM_ALIGNOF(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA); NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.depth = 1; NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.flags = 0;NTIv2__mQxM9c9bV7u4RrPbNPT1RJdA_.display = TM__M8fx9bXu9bLHGnuCFOJXouvA_16;
}

