/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@stypes.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@stypes.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg;
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__w6UPC5ZMftnk3t733umymw_2 = { 6 | NIM_STRLIT_FLAG, "String" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_3 = {6, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_2};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__w6UPC5ZMftnk3t733umymw_4 = { 6 | NIM_STRLIT_FLAG, "Number" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_5 = {6, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__w6UPC5ZMftnk3t733umymw_6 = { 6 | NIM_STRLIT_FLAG, "Object" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_7 = {6, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__w6UPC5ZMftnk3t733umymw_8 = { 5 | NIM_STRLIT_FLAG, "Array" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_9 = {5, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_8};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__w6UPC5ZMftnk3t733umymw_10 = { 4 | NIM_STRLIT_FLAG, "Bool" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_11 = {4, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_10};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__w6UPC5ZMftnk3t733umymw_12 = { 4 | NIM_STRLIT_FLAG, "Null" };
static const NimStringV2 TM__w6UPC5ZMftnk3t733umymw_13 = {4, (NimStrPayload*)&TM__w6UPC5ZMftnk3t733umymw_12};
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pkgZjson95serializationZtypes_u52)(tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg e_p0) {
	NimStringV2 result;
	switch (e_p0) {
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)0):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_3;
	}
	break;
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)1):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_5;
	}
	break;
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)2):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_7;
	}
	break;
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)3):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_9;
	}
	break;
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)4):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_11;
	}
	break;
	case ((tyEnum_JsonValueKind__xMfZbK4rL9bzqYowFMHElsg)5):
	{
		result = TM__w6UPC5ZMftnk3t733umymw_13;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
