/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@swriter.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@m..@s..@s..@s..@s..@s.nimble@spkgs2@sjson_serialization-0.4.2-2b26a9e0fc79638dbb9272fb4ab5a1d79264f938@sjson_serialization@swriter.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <exception>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA;
struct tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content;
struct RootObj;
struct TNimTypeV2;
struct tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ;
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg;
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w;
struct tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg;
struct NimStrPayload;
struct NimStringV2;
struct Exception;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA {
  NI len; tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content* p;
};
struct tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* stream;
	NIM_BOOL hasTypeAnnotations;
	NIM_BOOL hasPrettyOutput;
	tySequence__Y9cA0MUhmZzC5pppHZAV9cNA stack;
	NIM_BOOL empty;
	NIM_BOOL wantName;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w {
	NU8* startAddr;
	NU8* endAddr;
};
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA : public RootObj {
	tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ* vtable;
	tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers;
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w span;
	NI spanEndPos;
	NI extCursorsCount;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg {
	NI id;
	NimStringV2 name;
	NimStringV2 email;
	NIM_BOOL active;
};
struct tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw {
	NI rc;
};
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content { NI cap; tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*, eqdup___pkgZfaststreamsZoutputs_u132)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* src_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeRecordValue__businessZdata_u243)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* value_p1);
N_LIB_PRIVATE N_NIMCALL(void, beginObject__businessZdata_u249)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginObject__businessZdata_u254)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0);
N_LIB_PRIVATE N_NIMCALL(void, beginElement__businessZdata_u257)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u203)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, inArray__businessZdata_u265)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* w_p0);
static N_INLINE(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ, X5BX5D___businessZdata_u272)(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ* s_p0, NI s_p0Len_0, NI i_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pkgZfaststreamsZoutputs_u129)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*& dest_p0, tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeToNewSpan__pkgZfaststreamsZoutputs_u825)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8 b_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u126)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* dest_p0);
static N_INLINE(void, write__pkgZfaststreamsZoutputs_u969)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(void, write__pkgZfaststreamsZoutputs_u930)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NU8* bytes_p1, NI bytes_p1Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0);
static N_INLINE(NF, abs__system_u4370)(NF x_p0);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__businessZdata_u365)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA& x_p0, tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ y_p1);
N_LIB_PRIVATE N_NIMCALL(void, writeMember__businessZdata_u389)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 name_p1, NimStringV2 value_p2);
N_LIB_PRIVATE N_NIMCALL(void, writeName__businessZdata_u400)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 name_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, inObject__businessZdata_u404)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* w_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u516)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZfaststreamsZoutputs_u123)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, endElement__businessZdata_u770)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u852)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NI value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u8)(NI x_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u1003)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NIM_BOOL value_p1);
N_LIB_PRIVATE N_NIMCALL(void, endObject__businessZdata_u1033)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0);
static N_INLINE(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ, pop__businessZdata_u1036)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA& s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___businessZdata_u281)(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, shrink__businessZdata_u119)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA& x_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___businessZdata_u94)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_2 = { 36 | NIM_STRLIT_FLAG, "writer.nim(103, 3) `not w.wantName` " };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_3 = {36, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_6 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_7 = {1, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_6};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_10 = { 34 | NIM_STRLIT_FLAG, "writer.nim(191, 3) `w.inObject()` " };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_11 = {34, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_10};
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_12 = { 32 | NIM_STRLIT_FLAG, "writer.nim(192, 3) `w.wantName` " };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_13 = {32, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_12};
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_14 = {1, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_17 = { 4 | NIM_STRLIT_FLAG, "\\u00" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_18 = {4, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_17};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_19 = { 15 | NIM_STRLIT_FLAG, "0123456789abcde" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_20 = {15, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_19};
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_21 = {15, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_19};
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_22 = {15, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_19};
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_23 = {15, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_19};
static const struct {
  NI cap; NIM_CHAR data[93+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_24 = { 93 | NIM_STRLIT_FLAG, "iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_25 = {93, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_24};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_26 = { 5 | NIM_STRLIT_FLAG, "$type" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_27 = {5, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_26};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_28 = { 4 | NIM_STRLIT_FLAG, "User" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_29 = {4, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_28};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_30 = { 2 | NIM_STRLIT_FLAG, "id" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_31 = {2, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_30};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_32 = { 4 | NIM_STRLIT_FLAG, "name" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_33 = {4, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_32};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_34 = { 5 | NIM_STRLIT_FLAG, "email" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_35 = {5, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_34};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_36 = { 6 | NIM_STRLIT_FLAG, "active" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_37 = {6, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_36};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_38 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_39 = {4, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_38};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_40 = { 5 | NIM_STRLIT_FLAG, "false" };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_41 = {5, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_40};
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__RNMR7I3bvjA3IfNR8ijugg_43 = { 45 | NIM_STRLIT_FLAG, "writer.nim(143, 3) `w.stack.pop() == Object` " };
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_44 = {45, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_43};
static const NimStringV2 TM__RNMR7I3bvjA3IfNR8ijugg_45 = {1, (NimStrPayload*)&TM__RNMR7I3bvjA3IfNR8ijugg_6};
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, init__businessZdata_u64)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* stream_p1, NIM_BOOL pretty_p2, NIM_BOOL typeAnnotations_p3, tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* Result) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* colontmpD_;
	NIM_BOOL colontmpD__2;
	NIM_BOOL colontmpD__3;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = (NIM_BOOL)0;
	colontmpD__3 = (NIM_BOOL)0;
	nimZeroMem((void*)Result, sizeof(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg));
	colontmpD_ = eqdup___pkgZfaststreamsZoutputs_u132(stream_p1);
	(*Result).stream = colontmpD_;
	colontmpD__2 = pretty_p2;
	(*Result).hasPrettyOutput = colontmpD__2;
	colontmpD__3 = typeAnnotations_p3;
	(*Result).hasTypeAnnotations = colontmpD__3;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ, X5BX5D___businessZdata_u272)(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ* s_p0, NI s_p0Len_0, NI i_p1) {
	tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ result;
	NI TM__RNMR7I3bvjA3IfNR8ijugg_4;
	if (nimSubInt(s_p0Len_0, i_p1, &TM__RNMR7I3bvjA3IfNR8ijugg_4)) { raiseOverflow(); 	};
	if ((NI)(TM__RNMR7I3bvjA3IfNR8ijugg_4) < 0 || (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_4) >= s_p0Len_0){ raiseIndexError2((NI)(TM__RNMR7I3bvjA3IfNR8ijugg_4),s_p0Len_0-1); 	}
	result = s_p0[(NI)(TM__RNMR7I3bvjA3IfNR8ijugg_4)];
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, inArray__businessZdata_u265)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* w_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (*w_p0).stack.len;
	T1_ = (((NI)0) < T2_);
	if (!(T1_)) goto LA3_;
	T4_ = (tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)0;
	T4_ = X5BX5D___businessZdata_u272((((*w_p0).stack).p) ? ((*w_p0).stack.p->data) : NIM_NIL, (*w_p0).stack.len, ((NI)1));
	T1_ = (T4_ == ((tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)0));
LA3_: ;
	result = T1_;
	return result;
}
static N_INLINE(void, write__pkgZfaststreamsZoutputs_u969)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0, NimStringV2 value_p1) {
	NI TM__RNMR7I3bvjA3IfNR8ijugg_5;
	if (nimSubInt(value_p1.len, ((NI)1), &TM__RNMR7I3bvjA3IfNR8ijugg_5)) { raiseOverflow(); 	};
	if ((NI)(TM__RNMR7I3bvjA3IfNR8ijugg_5)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= value_p1.len || (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_5) < 0 || (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_5) >= value_p1.len)){ raiseIndexError4(((NI)0), (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_5), value_p1.len); 	}
	write__pkgZfaststreamsZoutputs_u930(s_p0, (((value_p1).p) ? ((NU8*)value_p1.p->data+(((NI)0))) : NIM_NIL), ((NI)(TM__RNMR7I3bvjA3IfNR8ijugg_5))-(((NI)0))+1);
}
static N_INLINE(NF, toFloat__system_u1676)(NI i_p0) {
	NF result;
	result = ((NF) (i_p0));
	return result;
}
static N_INLINE(NF, abs__system_u4370)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	auto T1_ = toFloat__system_u1676(a_p0);
	auto T2_ = toFloat__system_u1676(b_p1);
	NF floatProd = ((NF)(T1_) * (NF)(T2_));
	auto T3_ = toFloat__system_u1676(r);
	NF resAsFloat = T3_;
	{
		if (!(resAsFloat == floatProd)) goto LA6_;
{		(*res_p2) = r;
}	}
	goto LA4_;
LA6_: ;
	{
		{
			auto T11_ = abs__system_u4370(((NF)(resAsFloat) - (NF)(floatProd)));
			auto T12_ = abs__system_u4370(floatProd);
			if (!(((NF)(32.0) * (NF)(T11_)) <= T12_)) goto LA13_;
{			(*res_p2) = r;
}		}
		goto LA9_;
LA13_: ;
		{
			result = NIM_TRUE;
		}
LA9_: ;
	}
LA4_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	NI r = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
{		(*res_p2) = r;
}	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, beginElement__businessZdata_u257)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0) {
	{
		if (!!(!(w_p0.wantName))) goto LA3_;
{		failedAssertImpl__stdZassertions_u203(TM__RNMR7I3bvjA3IfNR8ijugg_3);
}	}
LA3_: ;
	{
		auto T7_ = inArray__businessZdata_u265((&w_p0));
		if (!T7_) goto LA8_;
{		{
			if (!w_p0.empty) goto LA12_;
{			w_p0.empty = NIM_FALSE;
}		}
		goto LA10_;
LA12_: ;
		{
			tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym12_;
			std::exception_ptr T16_;
			sX60gensym12_ = NIM_NIL;
			try {
			eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym12_), w_p0.stream);
			{
				if (!!(((*sX60gensym12_).span.startAddr == (*sX60gensym12_).span.endAddr))) goto LA19_;
{				(*(*sX60gensym12_).span.startAddr) = ((NU8)44);
				NU bytesX60gensym16_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
				(*sX60gensym12_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym12_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym16_))))))))));
}			}
			goto LA17_;
LA19_: ;
			{
				writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym12_, ((NU8)44));
			}
LA17_: ;
			}
			catch (Exception* T17_) {
			T16_ = std::current_exception();
			}
			catch (...) {
				T16_ = std::current_exception();
			}
			{
				eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym12_);
				if (T16_) std::rethrow_exception(T16_);
			}
		}
LA10_: ;
		{
			if (!w_p0.hasPrettyOutput) goto LA26_;
{			write__pkgZfaststreamsZoutputs_u969(w_p0.stream, TM__RNMR7I3bvjA3IfNR8ijugg_7);
			{
				NI iX60gensym4_;
				NI colontmp_;
				NI T29_;
				NI TM__RNMR7I3bvjA3IfNR8ijugg_8;
				iX60gensym4_ = (NI)0;
				colontmp_ = (NI)0;
				T29_ = w_p0.stack.len;
				if (nimMulInt(T29_, ((NI)2), &TM__RNMR7I3bvjA3IfNR8ijugg_8)) { raiseOverflow(); 				};
				colontmp_ = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_8);
				NI i = ((NI)0);
				{
					while (1) {
						tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym20_;
						std::exception_ptr T33_;
						NI TM__RNMR7I3bvjA3IfNR8ijugg_9;
						if (!(i < colontmp_)) goto LA31;
						sX60gensym20_ = NIM_NIL;
						try {
						iX60gensym4_ = i;
						eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym20_), w_p0.stream);
						{
							if (!!(((*sX60gensym20_).span.startAddr == (*sX60gensym20_).span.endAddr))) goto LA36_;
{							(*(*sX60gensym20_).span.startAddr) = ((NU8)32);
							NU bytesX60gensym24_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
							(*sX60gensym20_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym20_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym24_))))))))));
}						}
						goto LA34_;
LA36_: ;
						{
							writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym20_, ((NU8)32));
						}
LA34_: ;
						if (nimAddInt(i, ((NI)1), &TM__RNMR7I3bvjA3IfNR8ijugg_9)) { raiseOverflow(); 						};
						i = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_9);
						}
						catch (Exception* T34_) {
						T33_ = std::current_exception();
						}
						catch (...) {
							T33_ = std::current_exception();
						}
						{
							eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym20_);
							if (T33_) std::rethrow_exception(T33_);
						}
					} LA31: ;
				}
			}
}		}
LA26_: ;
}	}
LA8_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, beginObject__businessZdata_u254)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym27_;
	std::exception_ptr T2_;
	sX60gensym27_ = NIM_NIL;
	try {
	beginElement__businessZdata_u257((*(&w_p0)));
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym27_), w_p0.stream);
	{
		if (!!(((*sX60gensym27_).span.startAddr == (*sX60gensym27_).span.endAddr))) goto LA5_;
{		(*(*sX60gensym27_).span.startAddr) = ((NU8)123);
		NU bytesX60gensym31_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym27_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym27_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym31_))))))))));
}	}
	goto LA3_;
LA5_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym27_, ((NU8)123));
	}
LA3_: ;
	w_p0.empty = NIM_TRUE;
	w_p0.wantName = NIM_TRUE;
	add__businessZdata_u365((*(&w_p0.stack)), ((tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)1));
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym27_);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, inObject__businessZdata_u404)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* w_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (*w_p0).stack.len;
	T1_ = (((NI)0) < T2_);
	if (!(T1_)) goto LA3_;
	T4_ = (tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)0;
	T4_ = X5BX5D___businessZdata_u272((((*w_p0).stack).p) ? ((*w_p0).stack.p->data) : NIM_NIL, (*w_p0).stack.len, ((NI)1));
	T1_ = (T4_ == ((tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)1));
LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeName__businessZdata_u400)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 name_p1) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym56_;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym63_;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym70_;
	std::exception_ptr T2_;
	sX60gensym56_ = NIM_NIL;
	sX60gensym63_ = NIM_NIL;
	sX60gensym70_ = NIM_NIL;
	try {
	{
		auto T5_ = inObject__businessZdata_u404((&w_p0));
		if (!!(T5_)) goto LA6_;
{		failedAssertImpl__stdZassertions_u203(TM__RNMR7I3bvjA3IfNR8ijugg_11);
}	}
LA6_: ;
	{
		if (!!(w_p0.wantName)) goto LA10_;
{		failedAssertImpl__stdZassertions_u203(TM__RNMR7I3bvjA3IfNR8ijugg_13);
}	}
LA10_: ;
	w_p0.wantName = NIM_FALSE;
	{
		if (!w_p0.empty) goto LA14_;
{		w_p0.empty = NIM_FALSE;
}	}
	goto LA12_;
LA14_: ;
	{
		tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym41_;
		std::exception_ptr T18_;
		sX60gensym41_ = NIM_NIL;
		try {
		eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym41_), w_p0.stream);
		{
			if (!!(((*sX60gensym41_).span.startAddr == (*sX60gensym41_).span.endAddr))) goto LA21_;
{			(*(*sX60gensym41_).span.startAddr) = ((NU8)44);
			NU bytesX60gensym45_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
			(*sX60gensym41_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym41_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym45_))))))))));
}		}
		goto LA19_;
LA21_: ;
		{
			writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym41_, ((NU8)44));
		}
LA19_: ;
		}
		catch (Exception* T19_) {
		T18_ = std::current_exception();
		}
		catch (...) {
			T18_ = std::current_exception();
		}
		{
			eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym41_);
			if (T18_) std::rethrow_exception(T18_);
		}
	}
LA12_: ;
	{
		if (!w_p0.hasPrettyOutput) goto LA28_;
{		write__pkgZfaststreamsZoutputs_u969(w_p0.stream, TM__RNMR7I3bvjA3IfNR8ijugg_14);
		{
			NI iX60gensym7_;
			NI colontmp_;
			NI T31_;
			NI TM__RNMR7I3bvjA3IfNR8ijugg_15;
			iX60gensym7_ = (NI)0;
			colontmp_ = (NI)0;
			T31_ = w_p0.stack.len;
			if (nimMulInt(T31_, ((NI)2), &TM__RNMR7I3bvjA3IfNR8ijugg_15)) { raiseOverflow(); 			};
			colontmp_ = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_15);
			NI i = ((NI)0);
			{
				while (1) {
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym49_;
					std::exception_ptr T35_;
					NI TM__RNMR7I3bvjA3IfNR8ijugg_16;
					if (!(i < colontmp_)) goto LA33;
					sX60gensym49_ = NIM_NIL;
					try {
					iX60gensym7_ = i;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym49_), w_p0.stream);
					{
						if (!!(((*sX60gensym49_).span.startAddr == (*sX60gensym49_).span.endAddr))) goto LA38_;
{						(*(*sX60gensym49_).span.startAddr) = ((NU8)32);
						NU bytesX60gensym53_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym49_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym49_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym53_))))))))));
}					}
					goto LA36_;
LA38_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym49_, ((NU8)32));
					}
LA36_: ;
					if (nimAddInt(i, ((NI)1), &TM__RNMR7I3bvjA3IfNR8ijugg_16)) { raiseOverflow(); 					};
					i = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_16);
					}
					catch (Exception* T36_) {
					T35_ = std::current_exception();
					}
					catch (...) {
						T35_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym49_);
						if (T35_) std::rethrow_exception(T35_);
					}
				} LA33: ;
			}
		}
}	}
LA28_: ;
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym56_), w_p0.stream);
	{
		if (!!(((*sX60gensym56_).span.startAddr == (*sX60gensym56_).span.endAddr))) goto LA45_;
{		(*(*sX60gensym56_).span.startAddr) = ((NU8)34);
		NU bytesX60gensym60_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym56_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym56_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym60_))))))))));
}	}
	goto LA43_;
LA45_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym56_, ((NU8)34));
	}
LA43_: ;
	write__pkgZfaststreamsZoutputs_u969(w_p0.stream, name_p1);
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym63_), w_p0.stream);
	{
		if (!!(((*sX60gensym63_).span.startAddr == (*sX60gensym63_).span.endAddr))) goto LA50_;
{		(*(*sX60gensym63_).span.startAddr) = ((NU8)34);
		NU bytesX60gensym67_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym63_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym63_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym67_))))))))));
}	}
	goto LA48_;
LA50_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym63_, ((NU8)34));
	}
LA48_: ;
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym70_), w_p0.stream);
	{
		if (!!(((*sX60gensym70_).span.startAddr == (*sX60gensym70_).span.endAddr))) goto LA55_;
{		(*(*sX60gensym70_).span.startAddr) = ((NU8)58);
		NU bytesX60gensym74_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym70_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym70_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym74_))))))))));
}	}
	goto LA53_;
LA55_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym70_, ((NU8)58));
	}
LA53_: ;
	{
		tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym77_;
		std::exception_ptr T63_;
		if (!w_p0.hasPrettyOutput) goto LA60_;
{		sX60gensym77_ = NIM_NIL;
		try {
		eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym77_), w_p0.stream);
		{
			if (!!(((*sX60gensym77_).span.startAddr == (*sX60gensym77_).span.endAddr))) goto LA66_;
{			(*(*sX60gensym77_).span.startAddr) = ((NU8)32);
			NU bytesX60gensym81_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
			(*sX60gensym77_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym77_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym81_))))))))));
}		}
		goto LA64_;
LA66_: ;
		{
			writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym77_, ((NU8)32));
		}
LA64_: ;
		}
		catch (Exception* T64_) {
		T63_ = std::current_exception();
		}
		catch (...) {
			T63_ = std::current_exception();
		}
		{
			eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym77_);
			if (T63_) std::rethrow_exception(T63_);
		}
}	}
LA60_: ;
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym70_);
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym63_);
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym56_);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, endElement__businessZdata_u770)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0) {
	w_p0.wantName = inObject__businessZdata_u404((&w_p0));
}
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u516)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 value_p1) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym87_;
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym205_;
	std::exception_ptr T2_;
	s = NIM_NIL;
	sX60gensym87_ = NIM_NIL;
	sX60gensym205_ = NIM_NIL;
	try {
	beginElement__businessZdata_u257((*(&w_p0)));
	eqcopy___pkgZfaststreamsZoutputs_u129((*&s), w_p0.stream);
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym87_), s);
	{
		if (!!(((*sX60gensym87_).span.startAddr == (*sX60gensym87_).span.endAddr))) goto LA5_;
{		(*(*sX60gensym87_).span.startAddr) = ((NU8)34);
		NU bytesX60gensym91_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym87_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym87_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym91_))))))))));
}	}
	goto LA3_;
LA5_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym87_, ((NU8)34));
	}
LA3_: ;
	{
		NIM_CHAR cX60gensym12_;
		cX60gensym12_ = (NIM_CHAR)0;
		NI i = ((NI)0);
		NI L = value_p1.len;
		{
			while (1) {
				if (!(i < L)) goto LA10;
				if (i < 0 || i >= value_p1.len){ raiseIndexError2(i,value_p1.len-1); 				}
				cX60gensym12_ = value_p1.p->data[i];
				switch (((NU8)(cX60gensym12_))) {
				case 8:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym95_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym102_;
					std::exception_ptr T13_;
					sX60gensym95_ = NIM_NIL;
					sX60gensym102_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym95_), s);
					{
						if (!!(((*sX60gensym95_).span.startAddr == (*sX60gensym95_).span.endAddr))) goto LA16_;
{						(*(*sX60gensym95_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym99_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym95_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym95_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym99_))))))))));
}					}
					goto LA14_;
LA16_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym95_, ((NU8)92));
					}
LA14_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym102_), s);
					{
						if (!!(((*sX60gensym102_).span.startAddr == (*sX60gensym102_).span.endAddr))) goto LA21_;
{						(*(*sX60gensym102_).span.startAddr) = ((NU8)98);
						NU bytesX60gensym106_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym102_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym102_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym106_))))))))));
}					}
					goto LA19_;
LA21_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym102_, ((NU8)98));
					}
LA19_: ;
					}
					catch (Exception* T14_) {
					T13_ = std::current_exception();
					}
					catch (...) {
						T13_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym102_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym95_);
						if (T13_) std::rethrow_exception(T13_);
					}
				}
				break;
				case 9:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym110_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym117_;
					std::exception_ptr T28_;
					sX60gensym110_ = NIM_NIL;
					sX60gensym117_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym110_), s);
					{
						if (!!(((*sX60gensym110_).span.startAddr == (*sX60gensym110_).span.endAddr))) goto LA31_;
{						(*(*sX60gensym110_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym114_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym110_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym110_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym114_))))))))));
}					}
					goto LA29_;
LA31_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym110_, ((NU8)92));
					}
LA29_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym117_), s);
					{
						if (!!(((*sX60gensym117_).span.startAddr == (*sX60gensym117_).span.endAddr))) goto LA36_;
{						(*(*sX60gensym117_).span.startAddr) = ((NU8)116);
						NU bytesX60gensym121_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym117_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym117_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym121_))))))))));
}					}
					goto LA34_;
LA36_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym117_, ((NU8)116));
					}
LA34_: ;
					}
					catch (Exception* T29_) {
					T28_ = std::current_exception();
					}
					catch (...) {
						T28_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym117_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym110_);
						if (T28_) std::rethrow_exception(T28_);
					}
				}
				break;
				case 10:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym125_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym132_;
					std::exception_ptr T43_;
					sX60gensym125_ = NIM_NIL;
					sX60gensym132_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym125_), s);
					{
						if (!!(((*sX60gensym125_).span.startAddr == (*sX60gensym125_).span.endAddr))) goto LA46_;
{						(*(*sX60gensym125_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym129_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym125_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym125_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym129_))))))))));
}					}
					goto LA44_;
LA46_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym125_, ((NU8)92));
					}
LA44_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym132_), s);
					{
						if (!!(((*sX60gensym132_).span.startAddr == (*sX60gensym132_).span.endAddr))) goto LA51_;
{						(*(*sX60gensym132_).span.startAddr) = ((NU8)110);
						NU bytesX60gensym136_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym132_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym132_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym136_))))))))));
}					}
					goto LA49_;
LA51_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym132_, ((NU8)110));
					}
LA49_: ;
					}
					catch (Exception* T44_) {
					T43_ = std::current_exception();
					}
					catch (...) {
						T43_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym132_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym125_);
						if (T43_) std::rethrow_exception(T43_);
					}
				}
				break;
				case 12:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym140_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym147_;
					std::exception_ptr T58_;
					sX60gensym140_ = NIM_NIL;
					sX60gensym147_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym140_), s);
					{
						if (!!(((*sX60gensym140_).span.startAddr == (*sX60gensym140_).span.endAddr))) goto LA61_;
{						(*(*sX60gensym140_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym144_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym140_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym140_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym144_))))))))));
}					}
					goto LA59_;
LA61_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym140_, ((NU8)92));
					}
LA59_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym147_), s);
					{
						if (!!(((*sX60gensym147_).span.startAddr == (*sX60gensym147_).span.endAddr))) goto LA66_;
{						(*(*sX60gensym147_).span.startAddr) = ((NU8)102);
						NU bytesX60gensym151_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym147_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym147_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym151_))))))))));
}					}
					goto LA64_;
LA66_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym147_, ((NU8)102));
					}
LA64_: ;
					}
					catch (Exception* T59_) {
					T58_ = std::current_exception();
					}
					catch (...) {
						T58_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym147_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym140_);
						if (T58_) std::rethrow_exception(T58_);
					}
				}
				break;
				case 13:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym155_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym162_;
					std::exception_ptr T73_;
					sX60gensym155_ = NIM_NIL;
					sX60gensym162_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym155_), s);
					{
						if (!!(((*sX60gensym155_).span.startAddr == (*sX60gensym155_).span.endAddr))) goto LA76_;
{						(*(*sX60gensym155_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym159_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym155_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym155_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym159_))))))))));
}					}
					goto LA74_;
LA76_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym155_, ((NU8)92));
					}
LA74_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym162_), s);
					{
						if (!!(((*sX60gensym162_).span.startAddr == (*sX60gensym162_).span.endAddr))) goto LA81_;
{						(*(*sX60gensym162_).span.startAddr) = ((NU8)114);
						NU bytesX60gensym166_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym162_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym162_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym166_))))))))));
}					}
					goto LA79_;
LA81_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym162_, ((NU8)114));
					}
LA79_: ;
					}
					catch (Exception* T74_) {
					T73_ = std::current_exception();
					}
					catch (...) {
						T73_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym162_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym155_);
						if (T73_) std::rethrow_exception(T73_);
					}
				}
				break;
				case 34:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym170_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym177_;
					std::exception_ptr T88_;
					sX60gensym170_ = NIM_NIL;
					sX60gensym177_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym170_), s);
					{
						if (!!(((*sX60gensym170_).span.startAddr == (*sX60gensym170_).span.endAddr))) goto LA91_;
{						(*(*sX60gensym170_).span.startAddr) = ((NU8)92);
						NU bytesX60gensym174_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym170_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym170_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym174_))))))))));
}					}
					goto LA89_;
LA91_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym170_, ((NU8)92));
					}
LA89_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym177_), s);
					{
						if (!!(((*sX60gensym177_).span.startAddr == (*sX60gensym177_).span.endAddr))) goto LA96_;
{						(*(*sX60gensym177_).span.startAddr) = ((NU8)34);
						NU bytesX60gensym181_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym177_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym177_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym181_))))))))));
}					}
					goto LA94_;
LA96_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym177_, ((NU8)34));
					}
LA94_: ;
					}
					catch (Exception* T89_) {
					T88_ = std::current_exception();
					}
					catch (...) {
						T88_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym177_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym170_);
						if (T88_) std::rethrow_exception(T88_);
					}
				}
				break;
				case 0 ... 7:
				case 11:
				case 14 ... 31:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym184_;
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym191_;
					std::exception_ptr T103_;
					sX60gensym184_ = NIM_NIL;
					sX60gensym191_ = NIM_NIL;
					try {
					write__pkgZfaststreamsZoutputs_u969(s, TM__RNMR7I3bvjA3IfNR8ijugg_18);
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym184_), s);
					{
						if (!!(((*sX60gensym184_).span.startAddr == (*sX60gensym184_).span.endAddr))) goto LA106_;
{						if ((NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)) < 0 || (NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)) >= TM__RNMR7I3bvjA3IfNR8ijugg_20.len){ raiseIndexError2((NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)),TM__RNMR7I3bvjA3IfNR8ijugg_20.len-1); 						}
						(*(*sX60gensym184_).span.startAddr) = ((NU8) (((NU8)(TM__RNMR7I3bvjA3IfNR8ijugg_20.p->data[(NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15))]))));
						NU bytesX60gensym188_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym184_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym184_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym188_))))))))));
}					}
					goto LA104_;
LA106_: ;
					{
						if ((NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)) < 0 || (NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)) >= TM__RNMR7I3bvjA3IfNR8ijugg_21.len){ raiseIndexError2((NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15)),TM__RNMR7I3bvjA3IfNR8ijugg_21.len-1); 						}
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym184_, ((NU8) (((NU8)(TM__RNMR7I3bvjA3IfNR8ijugg_21.p->data[(NU8)((NU8)((NU8)(((NU8) (((NU8)(cX60gensym12_))))) >> (NU64)(((NI)4))) & ((NU8)15))])))));
					}
LA104_: ;
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym191_), s);
					{
						if (!!(((*sX60gensym191_).span.startAddr == (*sX60gensym191_).span.endAddr))) goto LA111_;
{						if ((NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)) < 0 || (NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)) >= TM__RNMR7I3bvjA3IfNR8ijugg_22.len){ raiseIndexError2((NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)),TM__RNMR7I3bvjA3IfNR8ijugg_22.len-1); 						}
						(*(*sX60gensym191_).span.startAddr) = ((NU8) (((NU8)(TM__RNMR7I3bvjA3IfNR8ijugg_22.p->data[(NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15))]))));
						NU bytesX60gensym195_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym191_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym191_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym195_))))))))));
}					}
					goto LA109_;
LA111_: ;
					{
						if ((NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)) < 0 || (NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)) >= TM__RNMR7I3bvjA3IfNR8ijugg_23.len){ raiseIndexError2((NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15)),TM__RNMR7I3bvjA3IfNR8ijugg_23.len-1); 						}
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym191_, ((NU8) (((NU8)(TM__RNMR7I3bvjA3IfNR8ijugg_23.p->data[(NU8)(((NU8) (((NU8)(cX60gensym12_)))) & ((NU8)15))])))));
					}
LA109_: ;
					}
					catch (Exception* T104_) {
					T103_ = std::current_exception();
					}
					catch (...) {
						T103_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym191_);
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym184_);
						if (T103_) std::rethrow_exception(T103_);
					}
				}
				break;
				default:
				{
					tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym198_;
					std::exception_ptr T118_;
					sX60gensym198_ = NIM_NIL;
					try {
					eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym198_), s);
					{
						if (!!(((*sX60gensym198_).span.startAddr == (*sX60gensym198_).span.endAddr))) goto LA121_;
{						(*(*sX60gensym198_).span.startAddr) = ((NU8) (((NU8)(cX60gensym12_))));
						NU bytesX60gensym202_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
						(*sX60gensym198_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym198_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym202_))))))))));
}					}
					goto LA119_;
LA121_: ;
					{
						writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym198_, ((NU8) (((NU8)(cX60gensym12_)))));
					}
LA119_: ;
					}
					catch (Exception* T119_) {
					T118_ = std::current_exception();
					}
					catch (...) {
						T118_ = std::current_exception();
					}
					{
						eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym198_);
						if (T118_) std::rethrow_exception(T118_);
					}
				}
				break;
				}
				i += ((NI)1);
				{
					if (!!((value_p1.len == L))) goto LA128_;
{					failedAssertImpl__stdZassertions_u203(TM__RNMR7I3bvjA3IfNR8ijugg_25);
}				}
LA128_: ;
			} LA10: ;
		}
	}
	sX60gensym205_ = s;
	eqwasMoved___pkgZfaststreamsZoutputs_u123((*&s));
	{
		if (!!(((*sX60gensym205_).span.startAddr == (*sX60gensym205_).span.endAddr))) goto LA132_;
{		(*(*sX60gensym205_).span.startAddr) = ((NU8)34);
		NU bytesX60gensym209_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym205_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym205_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym209_))))))))));
}	}
	goto LA130_;
LA132_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym205_, ((NU8)34));
	}
LA130_: ;
	endElement__businessZdata_u770((*(&w_p0)));
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym205_);
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym87_);
		eqdestroy___pkgZfaststreamsZoutputs_u126(s);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, writeMember__businessZdata_u389)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NimStringV2 name_p1, NimStringV2 value_p2) {
	{
		if (!NIM_TRUE) goto LA3_;
{		writeName__businessZdata_u400((*(&w_p0)), name_p1);
		writeValue__businessZdata_u516((*(&w_p0)), value_p2);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, beginObject__businessZdata_u249)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0) {
	beginObject__businessZdata_u254((*(&w_p0)));
	{
		if (!w_p0.hasTypeAnnotations) goto LA3_;
{		writeMember__businessZdata_u389((*(&w_p0)), TM__RNMR7I3bvjA3IfNR8ijugg_27, TM__RNMR7I3bvjA3IfNR8ijugg_29);
}	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u852)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NI value_p1) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s;
	NimStringV2 colontmpD_;
	std::exception_ptr T2_;
	s = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	try {
	beginElement__businessZdata_u257((*(&w_p0)));
	eqcopy___pkgZfaststreamsZoutputs_u129((*&s), w_p0.stream);
	colontmpD_ = dollar___systemZdollars_u8(value_p1);
	write__pkgZfaststreamsZoutputs_u969(s, colontmpD_);
	endElement__businessZdata_u770((*(&w_p0)));
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pkgZfaststreamsZoutputs_u126(s);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u1003)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, NIM_BOOL value_p1) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	std::exception_ptr T2_;
	NimStringV2 T3_;
	s = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	try {
	beginElement__businessZdata_u257((*(&w_p0)));
	eqcopy___pkgZfaststreamsZoutputs_u129((*&s), w_p0.stream);
	T3_.len = 0; T3_.p = NIM_NIL;
	{
		if (!value_p1) goto LA6_;
{		colontmpD_ = TM__RNMR7I3bvjA3IfNR8ijugg_39;
		T3_ = colontmpD_;
}	}
	goto LA4_;
LA6_: ;
	{
		colontmpD__2 = TM__RNMR7I3bvjA3IfNR8ijugg_41;
		T3_ = colontmpD__2;
	}
LA4_: ;
	write__pkgZfaststreamsZoutputs_u969(s, T3_);
	endElement__businessZdata_u770((*(&w_p0)));
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		eqdestroy___pkgZfaststreamsZoutputs_u126(s);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___businessZdata_u281)(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ& dest_p0) {
	dest_p0 = 0;
}
static N_INLINE(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ, pop__businessZdata_u1036)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA& s_p0) {
	tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ result;
	NI T1_;
	NI TM__RNMR7I3bvjA3IfNR8ijugg_42;
	T1_ = s_p0.len;
	if (nimSubInt(T1_, ((NI)1), &TM__RNMR7I3bvjA3IfNR8ijugg_42)) { raiseOverflow(); 	};
	NI L = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_42);
	if (L < 0 || L >= s_p0.len){ raiseIndexError2(L,s_p0.len-1); 	}
	result = s_p0.p->data[L];
	eqwasMoved___businessZdata_u281(s_p0.p->data[L]);
	if ((L) < ((NI)0) || (L) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(L, ((NI)0), ((NI)IL64(9223372036854775807))); 	}
	shrink__businessZdata_u119((*(&s_p0)), (L));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, endObject__businessZdata_u1033)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0) {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym248_;
	std::exception_ptr T2_;
	sX60gensym248_ = NIM_NIL;
	try {
	{
		auto T5_ = pop__businessZdata_u1036((*(&w_p0.stack)));
		if (!!((T5_ == ((tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ)1)))) goto LA6_;
{		failedAssertImpl__stdZassertions_u203(TM__RNMR7I3bvjA3IfNR8ijugg_44);
}	}
LA6_: ;
	{
		if (!!(w_p0.empty)) goto LA10_;
{		{
			if (!w_p0.hasPrettyOutput) goto LA14_;
{			write__pkgZfaststreamsZoutputs_u969(w_p0.stream, TM__RNMR7I3bvjA3IfNR8ijugg_45);
			{
				NI iX60gensym5_;
				NI colontmp_;
				NI T17_;
				NI TM__RNMR7I3bvjA3IfNR8ijugg_46;
				iX60gensym5_ = (NI)0;
				colontmp_ = (NI)0;
				T17_ = w_p0.stack.len;
				if (nimMulInt(T17_, ((NI)2), &TM__RNMR7I3bvjA3IfNR8ijugg_46)) { raiseOverflow(); 				};
				colontmp_ = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_46);
				NI i = ((NI)0);
				{
					while (1) {
						tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* sX60gensym241_;
						std::exception_ptr T21_;
						NI TM__RNMR7I3bvjA3IfNR8ijugg_47;
						if (!(i < colontmp_)) goto LA19;
						sX60gensym241_ = NIM_NIL;
						try {
						iX60gensym5_ = i;
						eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym241_), w_p0.stream);
						{
							if (!!(((*sX60gensym241_).span.startAddr == (*sX60gensym241_).span.endAddr))) goto LA24_;
{							(*(*sX60gensym241_).span.startAddr) = ((NU8)32);
							NU bytesX60gensym245_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
							(*sX60gensym241_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym241_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym245_))))))))));
}						}
						goto LA22_;
LA24_: ;
						{
							writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym241_, ((NU8)32));
						}
LA22_: ;
						if (nimAddInt(i, ((NI)1), &TM__RNMR7I3bvjA3IfNR8ijugg_47)) { raiseOverflow(); 						};
						i = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_47);
						}
						catch (Exception* T22_) {
						T21_ = std::current_exception();
						}
						catch (...) {
							T21_ = std::current_exception();
						}
						{
							eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym241_);
							if (T21_) std::rethrow_exception(T21_);
						}
					} LA19: ;
				}
			}
}		}
LA14_: ;
}	}
LA10_: ;
	w_p0.empty = NIM_FALSE;
	eqcopy___pkgZfaststreamsZoutputs_u129((*&sX60gensym248_), w_p0.stream);
	{
		if (!!(((*sX60gensym248_).span.startAddr == (*sX60gensym248_).span.endAddr))) goto LA31_;
{		(*(*sX60gensym248_).span.startAddr) = ((NU8)125);
		NU bytesX60gensym252_ = (NU)((NU64)(((NU) (((NI)1)))) * (NU64)(((NU)1)));
		(*sX60gensym248_).span.startAddr = ((NU8*) (((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (((void*) ((*sX60gensym248_).span.startAddr))))) + (NU64)(((NU) (((NI) (bytesX60gensym252_))))))))));
}	}
	goto LA29_;
LA31_: ;
	{
		writeToNewSpan__pkgZfaststreamsZoutputs_u825(sX60gensym248_, ((NU8)125));
	}
LA29_: ;
	endElement__businessZdata_u770((*(&w_p0)));
	}
	catch (Exception* T3_) {
	T2_ = std::current_exception();
	}
	catch (...) {
		T2_ = std::current_exception();
	}
	{
		eqdestroy___pkgZfaststreamsZoutputs_u126(sX60gensym248_);
		if (T2_) std::rethrow_exception(T2_);
	}
}
N_LIB_PRIVATE N_NIMCALL(void, writeRecordValue__businessZdata_u243)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* value_p1) {
	beginObject__businessZdata_u249((*(&w_p0)));
	{
		if (!NIM_TRUE) goto LA3_;
{		writeName__businessZdata_u400((*(&w_p0)), TM__RNMR7I3bvjA3IfNR8ijugg_31);
		beginElement__businessZdata_u257((*(&w_p0)));
		writeValue__businessZdata_u852((*(&w_p0)), (*value_p1).id);
		endElement__businessZdata_u770((*(&w_p0)));
}	}
LA3_: ;
	{
		if (!NIM_TRUE) goto LA7_;
{		writeName__businessZdata_u400((*(&w_p0)), TM__RNMR7I3bvjA3IfNR8ijugg_33);
		beginElement__businessZdata_u257((*(&w_p0)));
		writeValue__businessZdata_u516((*(&w_p0)), (*value_p1).name);
		endElement__businessZdata_u770((*(&w_p0)));
}	}
LA7_: ;
	{
		if (!NIM_TRUE) goto LA11_;
{		writeName__businessZdata_u400((*(&w_p0)), TM__RNMR7I3bvjA3IfNR8ijugg_35);
		beginElement__businessZdata_u257((*(&w_p0)));
		writeValue__businessZdata_u516((*(&w_p0)), (*value_p1).email);
		endElement__businessZdata_u770((*(&w_p0)));
}	}
LA11_: ;
	{
		if (!NIM_TRUE) goto LA15_;
{		writeName__businessZdata_u400((*(&w_p0)), TM__RNMR7I3bvjA3IfNR8ijugg_37);
		beginElement__businessZdata_u257((*(&w_p0)));
		writeValue__businessZdata_u1003((*(&w_p0)), (*value_p1).active);
		endElement__businessZdata_u770((*(&w_p0)));
}	}
LA15_: ;
	endObject__businessZdata_u1033((*(&w_p0)));
}
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u194)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* value_p1) {
	writeRecordValue__businessZdata_u243((*(&w_p0)), value_p1);
}
static N_INLINE(NI, minuspercent___system_u807)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
{		auto T5_ = minuspercent___system_u807(((NI) (ptrdiff_t) (p_p0)), ((NI)8));
		tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw* cell = ((tyObject_RefHeader__9aS4IqkAFGaYlutBChu3r9cw*) (T5_));
		{
			if (!((NI)((NI64)((*cell).rc) >> (NU64)(((NI)3))) == ((NI)0))) goto LA8_;
{			result = NIM_TRUE;
}		}
		goto LA6_;
LA8_: ;
		{
			NI TM__RNMR7I3bvjA3IfNR8ijugg_48;
			if (nimSubInt((*cell).rc, ((NI)8), &TM__RNMR7I3bvjA3IfNR8ijugg_48)) { raiseOverflow(); 			};
			(*cell).rc = (NI)(TM__RNMR7I3bvjA3IfNR8ijugg_48);
		}
LA6_: ;
}	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___businessZdata_u94)(tySequence__Y9cA0MUhmZzC5pppHZAV9cNA dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___businessZdata_u76)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& dest_p0) {
	{
		auto T3_ = nimDecRefIsLast(dest_p0.stream);
		if (!T3_) goto LA4_;
{		nimDestroyAndDispose(dest_p0.stream);
}	}
LA4_: ;
	eqdestroy___businessZdata_u94(dest_p0.stack);
}
