/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@mbusiness@sdata.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@mbusiness@sdata.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <exception>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg;
struct tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw;
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA;
struct tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content;
struct RootObj;
struct TNimTypeV2;
struct tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ;
struct tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg;
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w;
struct Exception;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg {
	NI id;
	NimStringV2 name;
	NimStringV2 email;
	NIM_BOOL active;
};
struct tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s;
};
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA {
  NI len; tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content* p;
};
struct tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg {
	tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* stream;
	NIM_BOOL hasTypeAnnotations;
	NIM_BOOL hasPrettyOutput;
	tySequence__Y9cA0MUhmZzC5pppHZAV9cNA stack;
	NIM_BOOL empty;
	NIM_BOOL wantName;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w {
	NU8* startAddr;
	NU8* endAddr;
};
struct tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA : public RootObj {
	tyObject_OutputStreamVTable__PJLNQvanVJBTUPhrxceN9cQ* vtable;
	tyObject_PageBufferscolonObjectType___fWRbk0X2bU9brfPa7XfkUsg* buffers;
	tyObject_PageSpan__mpqYzXgomzyNzltOaGCp3w span;
	NI spanEndPos;
	NI extCursorsCount;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w : public Exception {
};
typedef NU8 tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ;
struct tySequence__Y9cA0MUhmZzC5pppHZAV9cNA_Content { NI cap; tyEnum_CollectionKind__hDt1P29cdSer9aLjKJXUfQTQ data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2612)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2609)(NimStringV2& dest_p0, NimStringV2 src_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, memoryOutput__pkgZfaststreamsZoutputs_u184)(NI pageSize_p0, tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw* Result);
N_LIB_PRIVATE N_NIMCALL(void, init__businessZdata_u64)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* stream_p1, NIM_BOOL pretty_p2, NIM_BOOL typeAnnotations_p3, tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA*, implicitDeref__pkgZfaststreamsZoutputs_u120)(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw h_p0);
N_LIB_PRIVATE N_NIMCALL(void, writeValue__businessZdata_u194)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& w_p0, tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getOutput__businessZdata_u1104)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u126)(tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___businessZdata_u76)(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg& dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZfaststreamsZoutputs_u197)(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw& dest_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u206)(Exception*& dest_p0, Exception* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1887)(NimStringV2 s_p0, NimStringV2 sub_p1);
extern TNimTypeV2 NTIv2__3XF2pFjTmVrdJNEfAv9c60w_;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xbm1iz8rnKdJ49aJccfck9ag_2 = { 1 | NIM_STRLIT_FLAG, "@" };
static const NimStringV2 TM__xbm1iz8rnKdJ49aJccfck9ag_3 = {1, (NimStrPayload*)&TM__xbm1iz8rnKdJ49aJccfck9ag_2};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__xbm1iz8rnKdJ49aJccfck9ag_4 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__xbm1iz8rnKdJ49aJccfck9ag_5 = {1, (NimStrPayload*)&TM__xbm1iz8rnKdJ49aJccfck9ag_4};
extern NIM_THREADVAR Exception* currException__system_u3314;
N_LIB_PRIVATE N_NIMCALL(void, createUser__businessZdata_u8)(NI id_p0, NimStringV2 name_p1, NimStringV2 email_p2, tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* Result) {
	NI colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
{	colontmpD_ = (NI)0;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD_ = id_p0;
	(*Result).id = colontmpD_;
	colontmpD__2 = eqdup___system_u2612(name_p1);
	(*Result).name = colontmpD__2;
	colontmpD__3 = eqdup___system_u2612(email_p2);
	(*Result).email = colontmpD__3;
	(*Result).active = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	auto T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3314;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u206((*&currException__system_u3314), (*currException__system_u3314).up);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, userToJson__businessZdata_u34)(tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg* user_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
{	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NimStringV2 colontmpD_;
		std::exception_ptr T4_;
		NimStringV2 T5_;
		std::exception_ptr T7_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		try {
		T5_.len = 0; T5_.p = NIM_NIL;
		try {
			tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw sX60gensym0_;
			tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg writerX60gensym0_;
			tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* colontmpD__2;
			tyObject_OutputStreamcolonObjectType___mQxM9c9bV7u4RrPbNPT1RJdA* colontmpD__3;
			std::exception_ptr T10_;
			nimZeroMem((void*)(&sX60gensym0_), sizeof(tyObject_OutputStreamHandle__zwx6DcPfEAp07Yp2r0d7rw));
			nimZeroMem((void*)(&writerX60gensym0_), sizeof(tyObject_JsonWriter__R5kF0MOd54LTv4cmXrGklg));
			colontmpD__2 = NIM_NIL;
			colontmpD__3 = NIM_NIL;
			try {
			memoryOutput__pkgZfaststreamsZoutputs_u184(((NI)4064), (&sX60gensym0_));
			colontmpD__2 = implicitDeref__pkgZfaststreamsZoutputs_u120(sX60gensym0_);
			init__businessZdata_u64(colontmpD__2, NIM_FALSE, NIM_FALSE, (&writerX60gensym0_));
			writeValue__businessZdata_u194((*(&writerX60gensym0_)), user_p0);
			colontmpD__3 = implicitDeref__pkgZfaststreamsZoutputs_u120(sX60gensym0_);
			colontmpD_ = getOutput__businessZdata_u1104(colontmpD__3);
			T5_ = colontmpD_;
			}
			catch (Exception* T11_) {
			T10_ = std::current_exception();
			}
			catch (...) {
				T10_ = std::current_exception();
			}
			{
				eqdestroy___pkgZfaststreamsZoutputs_u126(colontmpD__3);
				eqdestroy___pkgZfaststreamsZoutputs_u126(colontmpD__2);
				eqdestroy___businessZdata_u76((*(&writerX60gensym0_)));
				eqdestroy___pkgZfaststreamsZoutputs_u197((*(&sX60gensym0_)));
				if (T10_) std::rethrow_exception(T10_);
			}
		}
		catch (Exception* T8_) {
		T7_ = std::current_exception();
		if (isObjDisplayCheck(nimBorrowCurrentException()->m_type, 3, 371506688)) {
			tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w* T14_;
			T7_ = nullptr;
			T14_ = NIM_NIL;
			T14_ = (tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w*) nimNewObj(sizeof(tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w), NIM_ALIGNOF(tyObject_Defect__3XF2pFjTmVrdJNEfAv9c60w));
			(*T14_).m_type = (&NTIv2__3XF2pFjTmVrdJNEfAv9c60w_);
			(*T14_).name = "Defect";
			popCurrentException();
			raiseExceptionEx((Exception*)T14_, "Defect", "userToJson", "serialization.nim", 24);
			popCurrentException();
		}
		else throw;
		}
		eqcopy___system_u2609((*(&result)), T5_);
		}
		catch (Exception* T5_) {
		T4_ = std::current_exception();
		}
		catch (...) {
			T4_ = std::current_exception();
		}
		{
			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			if (T4_) std::rethrow_exception(T4_);
		}
	}
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___businessZdata_u16)(tyObject_User__f6PlpG8HkkZuH5Hx2Zl1Tg& dest_p0) {
	if (dest_p0.name.p && !(dest_p0.name.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.name.p);
}
	if (dest_p0.email.p && !(dest_p0.email.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.email.p);
}
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateEmail__businessZdata_u4083)(NimStringV2 email_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = contains__pureZstrutils_u1887(email_p0, TM__xbm1iz8rnKdJ49aJccfck9ag_3);
	if (!(T1_)) goto LA2_;
	T1_ = contains__pureZstrutils_u1887(email_p0, TM__xbm1iz8rnKdJ49aJccfck9ag_5);
LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
