/* Generated by Nim Compiler v2.2.0 */
/* Compiled for: iOS, arm64, clang */
/* Command for C compiler:
   clang++ -c -std=gnu++17 -funsigned-char  -pthread -fPIC  -O3 -fno-ident  -fPIC  -I/opt/homebrew/Cellar/nim/2.2.0/nim/lib -I/Users/siddarthkumar/code/siddarthkay/react-native-nim/nim-core/src -o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@mmain.nim.cpp.o /Users/siddarthkumar/code/siddarthkay/react-native-nim/bindings/ios/@mmain.nim.cpp */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
struct NimStrPayload;
struct NimStringV2;
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ;
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA;
struct Exception;
struct RootObj;
struct TNimTypeV2;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ;
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content;
struct tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA;
struct tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ;
struct tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg;
struct tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ;
struct tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw;
struct tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw;
struct tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg;
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void** vTable;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ {
  NI len; tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content* p;
};
struct Exception : public RootObj {
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__U3NvoVpKEobw8JVQGjnwkQ trace;
	Exception* up;
};
struct tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA : public Exception {
};
struct tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ : public tyObject_CatchableError__efF41ryIKUEBXF9csvj8HfA {
};
struct tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__U3NvoVpKEobw8JVQGjnwkQ_Content { NI cap; tyObject_StackTraceEntry__XJPlpMU9cDRJgRZvaiJYQVA data[SEQ_DECL_SIZE]; };
extern "C" N_LIB_EXPORT N_CDECL(NCSTRING, getNimCoreVersion)(void);
N_LIB_PRIVATE N_NIMCALL(void, chckNilDisp)(void* p_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u187)(tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseObjectConversionError)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u154)(tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u347)(tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u314)(tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u281)(tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u243)(tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZjson95serializationZreader95desc_u77)(tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZserializationZerrors_u4)(tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ* err_p0, NimStringV2 filename_p1);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystematsexceptionsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsinputsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_EXPORT N_CDECL(NCSTRING, getNimCoreVersion)(void) {
	NCSTRING result;
{	result = "1.0.0";
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, NimDestroyGlobals)(void) {
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatMsg__pkgZserializationZerrors_u8)(tyObject_SerializationError__qUdhKP7B9cID5naBoV5roXQ* err_p0, NimStringV2 filename_p1) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	chckNilDisp(err_p0);
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 4290907904)))) goto LA3_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 4290907904)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u187(((tyObject_UnexpectedTokenError__Yf9cCD9ayIXQm9ck469bHTCAVA*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA3_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 2844463360)))) goto LA6_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 2844463360)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u154(((tyObject_UnexpectedField__VamLEcYl0gEsW6NnIfR4FQ*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA6_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 856275456)))) goto LA9_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 856275456)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u347(((tyObject_IncompleteObjectError__tTMJuiAlyD9aK1bygUiUmTg*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA9_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 2996318208)))) goto LA12_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 2996318208)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u314(((tyObject_UnexpectedValueError__NLKYMMYEER259b5JqZxeHOQ*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA12_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 2173349888)))) goto LA15_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 2173349888)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u281(((tyObject_IntOverflowError__ZoGKsF9cUDumuitpao9cyyGw*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA15_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 6, 3307974144)))) goto LA18_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 6, 3307974144)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u243(((tyObject_GenericJsonReaderError__U8UrrucUHABmlNsn9bXfQKw*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA18_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 5, 3931547648)))) goto LA21_;
{		if (err_p0 && !isObjDisplayCheck((*err_p0).m_type, 5, 3931547648)){ raiseObjectConversionError(); 		}
		result = formatMsg__pkgZjson95serializationZreader95desc_u77(((tyObject_JsonReaderError__a9bpWqE6dc4xznuDs51nfmg*) (err_p0)), filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA21_: ;
	{
		if (!((err_p0) && (isObjDisplayCheck((*err_p0).m_type, 3, 1197549568)))) goto LA24_;
{		result = formatMsg__pkgZserializationZerrors_u4(err_p0, filename_p1);
		goto BeforeRet_;
}	}
	goto LA1_;
LA24_: ;
LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsinputsdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_Init000();
}

N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystematsexceptionsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_DatInit000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystematsexceptionsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsoptatshomebrewatsCellaratsnimats2dot2dot0atsnimatslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsfaststreamsminus0dot3dot0minus537acd856f131772e5553318f53bf1263935034aatsfaststreamsatsoutputsdotnim_DatInit000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

