// Auto-generated TypeScript interface for Nim bridge
// DO NOT EDIT MANUALLY - Generated by tools/generate_bindings.py
// This file will be overwritten when bindings are regenerated

export interface NimBridge {
  helloWorld(): string;
  addNumbers(a: number, b: number): number;
  getSystemInfo(): string;
  mobileFibonacci(n: number): number;
  mobileIsPrime(n: number): number;
  mobileFactorize(n: number): string;
  mobileCreateUser(id: number, name: string, email: string): string;
  mobileValidateEmail(email: string): number;
  getNimCoreVersion(): string;
}
